### PR TITLE
md basic start

### LINKED ISSUE #304: Hello world message for markdown
Write a program that generates hello world message in markdown.

Use any approach you like.

### PR DESCRIPTION
**Pull request by UnevenCoder**
resolve #304 

this simply console . logs 

later will work on creating a new md file and place this content in it :)

### CODE REVIEW

**Comment by tolgaerdonmez** [comment]
I think it should export function **markdown** as default

**Review by tolgaerdonmez — CHANGES_REQUESTED** [review]
Default export of markdown

**Comment by UnevenCoder** [comment]
> Default export of markdown
nope spoke with proful today

we will be creating a md file with this data later

**Review by EYRAM565 — APPROVED** [review]

**Comment by UnevenCoder** [comment]
@tolgaerdonmez you suggested empty changes :)

**Review by praveen2896 — APPROVED** [review]

**Comment by UnevenCoder** [comment]
2 approved waiting to be merged  @proful @johnjacobkenny

**Pull request merged**
