### PR TITLE
Small changes, mock data for the new format

### PR DESCRIPTION
**Pull request by PuruVJ**
Nothing much here, some typing changes, made a mock file for the data that the render function takes

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
I think that the renderer should not worry about twitter api response format. I think there should be some transformation from the twitter response into the renderer specific format.

Also the puppeteer scraped response should return the same format.

Twitter API | Puppeteer --> Common format --> handlebars template

**Comment by PuruVJ** [comment]
@johnjacobkenny The mock.json does contain the common format. For all the file formats.

**Comment by johnjacobkenny** [comment]
I'm seeing a lot of fields that's why I asked. Doubtful whether that level of granularity will be possible from scraping

**Comment by PuruVJ** [comment]
@johnjacobkenny 
Those extra fields you're seeing are just in the user object. They need to be refined.

Part of my next work😉

**Comment by PuruVJ** [comment]
@johnjacobkenny Can you merge it if its fine?

**Review by johnjacobkenny — APPROVED** [review]

**Pull request merged**
