### PR TITLE
Basic Images, GIFs, and Video preview URLs rendered

### PR DESCRIPTION
**Pull request by PuruVJ**
## Description
Basic Images, GIFs, and Video preview URLs rendering is in place now. Only evolution is left 🤣

## Attach Screenshot
Zoomed out version
image

The PDF itself: 
[simon.pdf](https://github.com/twindle-co/twindle/files/5499145/simon.pdf)

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
On fire @PuruVJ :fire:

**Comment by PuruVJ** [comment]
@johnjacobkenny Feeling like it!!!!

**Comment by PuruVJ** [comment]
Can't do much about page cutting as the most you can do is ask the browser to try not to cut content in between. Browser will try, but in the end, it'll have to cut.

**Comment by johnjacobkenny** [comment]
Ah

**Pull request merged**
