### PR TITLE
Added my name to team.md

### PR DESCRIPTION
**Pull request by sippeybro**
updated format

### CODE REVIEW

**Review by EYRAM565 — APPROVED** [review]

**Review by sarathkumar6 — CHANGES_REQUESTED** [review]
Hey @sippeybro, Do you mind keeping the document consistent by sticking to bullet point addition instead of |sippeBro| im sippey bro. know HTML CSS and basic javascript and php.|?
Stick with
Sippey Bro, im sippey bro. know HTML CSS and basic javascript and php

Thanks.

**Comment by sippeybro** [comment]
Updated pls check

**Review by pranavgoel29 — CHANGES_REQUESTED** [review]
Can you please pull the changes from main repo to your forked repo as I can see there is no table syntax in other names in your file that you have commited.

**Comment by tusharkandpal** [comment]
Please resolve conflicts to merge it.

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
@sippeybro the table format is broken & before that you need to pull all the changes done to **TEAM.md file** & resolve your merge conflict accordingly

**Comment by sippeybro** [comment]
@Akshay2996 pls check

**Comment by madhusudanbabar** [comment]
@sippeybro again conflicts, I guess you have not pulled the latest changes, there is no table structure in your code

**Pull request closed without merging**
