### PR TITLE
header2.html

### PR DESCRIPTION
**Pull request by satyaki07**
Added a header section. Also updated the naming conventions for files, pull requests and commit messages.

### CODE REVIEW

**Comment by satyaki07** [comment]
> Please check this and comment

Also added Naming conventions for files, pull requests and commit messages.

**Comment by arthurbuhl** [comment]
Duplicate of #317

**Comment by satyaki07** [comment]
Should I comment over there?

**Comment by tusharkandpal** [comment]
@satyaki07 use header2 as file names... Because swati and i already created ... It will avoid conflicts

**Comment by satyaki07** [comment]
okay, I have changed it to header2

**Comment by proful** [comment]
@satyaki07  great work!!

Pls get 2 approval. I'm waiting to merge!

**Review by tusharkandpal — APPROVED** [review]

**Review by pranavgoel29 — APPROVED** [review]

**Comment by satyaki07** [comment]
@proful I think the changes have been approved.

**Review by tusharkandpal — APPROVED** [review]
All good ✅ 👍

**Review by piratelicorne — APPROVED** [review]

**Pull request merged**
