### PR TITLE
Twindle website

### PR DESCRIPTION
**Pull request by UnevenCoder**
Following the design and remaking the website .. since reviewing will be alot in that sense creating a pr after each section :)

Not yet completely responsive 
image

### CODE REVIEW

**Comment by UnevenCoder** [comment]
@JoelVinayKumar

**Comment by JoelVinayKumar** [comment]
Please create separate issues for each section

**Comment by UnevenCoder** [comment]
close #625

**Comment by UnevenCoder** [comment]
done @JoelVinayKumar

**Comment by proful** [comment]
As we are working on phase 1
Convert to PDF not needed
Should be replaced with Email
@JoelVinayKumar @UnevenCoder

**Comment by UnevenCoder** [comment]
I  am not sure , I followed the design 
image

**Comment by proful** [comment]
@vasudeveloper001 please review

earlier code using html5 section etc looks much better

**Comment by UnevenCoder** [comment]
What do you mean looks better ?

**Comment by proful** [comment]
image
section vs div

I think you are referring wrong design. Below u should refer

image

**Comment by UnevenCoder** [comment]
@JoelVinayKumar created a design file for the project , I followed it ..
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

**Comment by proful** [comment]
@UnevenCoder scroll to right 😊 in the same figma

**Comment by UnevenCoder** [comment]
wait yea unnecessary time waste :( , will close the pull request then

**Pull request closed without merging**
