### PR TITLE
add my info in team.md

### PR DESCRIPTION
**Pull request by samueladeniyi**

### CODE REVIEW

**Review by shekhar10feb — APPROVED** [review]

**Review by Neaz-Mahmood — APPROVED** [review]

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
Hi @samueladeniyi Please see the Wiki Page of [Resolving Merge Conflicts](https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts)

Do not edit all the details just add your own details.

**Comment by samueladeniyi** [comment]
> Hi @samueladeniyi Please see the Wiki Page of [Resolving Merge Conflicts](https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts)
> 
> Do not edit all the details just add your own details.

ok, i will thanks

**Review by Akshay2996 — APPROVED** [review]
It looks good now👍

**Comment by samueladeniyi** [comment]
still conflicting, let me try again

**Pull request closed without merging**
