### PR TITLE
First PR

### PR DESCRIPTION
**Pull request by chimdie**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Do you want to add some details about yourself

**Comment by chimdie** [comment]
This is really going well

**Review by nishanknavelkar — APPROVED** [review]
Try Adding some details,
Name, Place where you are from, experience

**Review by UnevenCoder — CHANGES_REQUESTED** [review]
Try something like 

I am ....
I live in ...
I am this many years old
I love ...
I am learning ...

you can fill ur info in ... and commit again

**Comment by nishanknavelkar** [comment]
Also if unsure, you can have a look at this video,
https://www.youtube.com/watch?v=bzaBiQQl6fU&ab_channel=Twindle

**Review by EYRAM565 — APPROVED** [review]

**Review by chimdie — COMMENTED** [review]
This has been going well thus far

**Pull request closed without merging**
