### PR TITLE
Create deepak.md

### PR DESCRIPTION
**Pull request by deep0713**
PR-1

### CODE REVIEW

**Review by RafaelBatman55 — APPROVED** [review]

**Comment by sammjainn** [comment]
You have marked this as draft. When done with changes, select ready for review.

**Comment by UnevenCoder** [comment]
Hey you still haven't changed this so this can't be approved

**Comment by deep0713** [comment]
> You have marked this as draft. When done with changes, select ready for review.



> You have marked this as draft. When done with changes, select ready for review.

How did you know i marked it as draft

**Review by pranavgoel29 — APPROVED** [review]
It's good to go now 😄

**Pull request merged**
