### PR TITLE
second-pr

### PR DESCRIPTION
**Pull request by MumbiGachomba04**
This is my second pull request

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Good job @MumbiGachomba04 could you ask on the group for others to review

**Review by arthurbuhl — APPROVED** [review]
This looks good to me. I think this can be merged now.

**Review by tusharkandpal — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Thanks @arthurbuhl, are you on twitter, could you DM me, @johnjacobkenny is my id.

**Review by tusharkandpal — COMMENTED** [review]
good to go 👍

**Comment by johnjacobkenny** [comment]
Thanks @tusharkandpal

**Comment by MumbiGachomba04** [comment]
Thanks @johnjacobkenny 
@arthurbuhl and @tusharkandpal  already reviewed .... Is there need for more reviews?

**Comment by MumbiGachomba04** [comment]
Also @johnjacobkenny  I have sent you a twitter DM .I need help with keep my branch updated. so far it's 206 commits behind

**Comment by MumbiGachomba04** [comment]
keeping*

**Comment by tusharkandpal** [comment]
It's merged now. no need for more reviews
You can update your forked repo by going through #41

**Comment by arthurbuhl** [comment]
You can also checkout these videos by @sammjainn 

### Second PR from Git Bash

[ALT TEXT](https://www.youtube.com/watch?v=MUGhso65ub8&t=262s)

### Third PR from VS Code

[ALT TEXT](https://www.youtube.com/watch?v=DGKGgXnP8Po)

**Comment by MumbiGachomba04** [comment]
on it. thanks guys

**Pull request merged**
