### PR TITLE
Create mumbi.md

### PR DESCRIPTION
**Pull request by MumbiGachomba04**

### CODE REVIEW

**Comment by arthurbuhl** [comment]
Please update the file as follow:

- Rename the file from `Mumbi.md` to lowercase `mumbi.md` 
- Add some text inside the `mumbi.md` file like few lines introducing yourself to the community.

Thanks!

**Comment by proful** [comment]
Thanks @arthurbuhl for the review. I really appreciate it.

**Comment by johnjacobkenny** [comment]
Congrats @MumbiGachomba04 :partying_face: 

Thanks @arthurbuhl :+1:

**Comment by johnjacobkenny** [comment]
@MumbiGachomba04 please make the file name change :smiley:

**Comment by MumbiGachomba04** [comment]
I will close this pr and open another one with the correct name convention

**Review by pranavgoel29 — APPROVED** [review]
As I can see the name has been changed now, it is ready to merge.

**Comment by johnjacobkenny** [comment]
Thanks @arthurbuhl @pranavgoel29

**Comment by johnjacobkenny** [comment]
@arthurbuhl Thanks for helping out around this repo, curious to know who you are and how you came across this repo ❤️

**Comment by arthurbuhl** [comment]
Hi, I am Arthur Buhl. Web developer with basic knowledge of HTML, CSS and JS. I came to know about this repo through twitter and just wanted to contribute and trying to help new devs who are trying to know more about GitHub.

**Comment by MumbiGachomba04** [comment]
Thank you so much guys for the help 🤗

**Comment by johnjacobkenny** [comment]
Awesome! If you're on twitter could you please DM me my @ is johnjacobkenny

**Pull request merged**
