### PR TITLE
 Updated my info in TEAM.md in table format

### PR DESCRIPTION
**Pull request by SwatiRaoDataEnthusiast**
Please review the changes and accept

### CODE REVIEW

**Review by Akshay2996 — APPROVED** [review]

**Review by sarathkumar6 — APPROVED** [review]

**Review by sarathkumar6 — CHANGES_REQUESTED** [review]
Please keep the file name to small case instead of snake_case. Thanks

**Review by michaelcosj — APPROVED** [review]
Looks good!

**Comment by SwatiRaoDataEnthusiast** [comment]
@sarathkumar6 can you specify about which file name are you talking about ?

**Comment by sarathkumar6** [comment]
@SwatiRaoDataEnthusiast  the firstpr file name
from swati_rao to swatirao?

**Comment by tusharkandpal** [comment]
@sarathkumar6 people are naming it like this because of NAMING-CONVENTIONS.md file... We should make changes there

**Comment by sarathkumar6** [comment]
@tusharkandpal  Barring a few files, rest of the files in the firstpr folder follows small case convention. 
So, better to stick with the convention followed in the folder I feel. Instead of looking outside the folder. 
eventually we would want to follow same standards across; bit for now we could stick to what's followed inside the folder
https://github.com/twindle-co/twindle/tree/main/firstpr

**Comment by tusharkandpal** [comment]
Yes i agree...i was saying to correct the guidelines in there.

**Comment by sarathkumar6** [comment]
Sure, we will. But for now, we could stop one more change for the future now with this; that's the thought process behind it.

**Pull request closed without merging**
