### PR TITLE
[USER ACTION] My First PR to Twindle - Open Source Project

### PR DESCRIPTION
**Pull request by Akshay2996**
This is my first Pull Request to Twindle - Open Source Project which gives us the developer a platform to learn & build an app together & contribute towards the open source project.

### CODE REVIEW

**Comment by pranavgoel29** [comment]
Congrats on first PR to Twindle. 😄

**Comment by Akshay2996** [comment]
Created a new Resources.md file to get beginners started with the project by learning technologies like node.js, Javascript, git etc.

This file currently contains some Youtube links to get yourself started but you can also add some Blogpost here.

**Comment by proful** [comment]
Following Readme and contribution file naming convention use all upper case for file name.

Not sure whether to use this file or wiki. We need to discuss pros and cons.

**Comment by proful** [comment]
I think wiki is not a good idea.
Use
https://github.com/twindle-co/twindle/blob/main/docs/RESOURCES.md

**Comment by johnjacobkenny** [comment]
> I think wiki is not a good idea.
> Use
> https://github.com/twindle-co/twindle/blob/main/docs/RESOURCES.md

@proful could you elaborate? Is it because everyone can't pitch in?

**Comment by proful** [comment]
Yes I don't know how others can push their changes.

Creating files is better imo

**Comment by Akshay2996** [comment]
Yes @proful we cannot change the wiki page of twindle. We can only create pull request to the main repository.

**Comment by Akshay2996** [comment]
I have made changes to this PR. Please review it @proful @johnjacobkenny @sarathkumar6

**Comment by proful** [comment]
Yes

Update the resources.md under docs

**Pull request merged**
