### PR TITLE
Second PR

### PR DESCRIPTION
**Pull request by vasudeveloper001**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Few lines are removed from FAQ?

**Comment by vasudeveloper001** [comment]
No. I added few lines in FAQ. Line 66 to 69, I think.

**Comment by johnjacobkenny** [comment]
@pranavgoel29 could you review

**Comment by sarathkumar6** [comment]
@johnjacobkenny Just the empty lines were removed, no content is affected. Looks good to me

**Comment by pranavgoel29** [comment]
@johnjacobkenny no line were removed he just shifted some line down and he also added 4 lines, but the video link is not there. After he wroted that Here the video link.

**Comment by johnjacobkenny** [comment]
@vasudeveloper001 please add the link

**Review by thunder-coding — APPROVED** [review]

**Pull request merged**
