### PR TITLE
Create sachin.md

### PR DESCRIPTION
**Pull request by toocoolsachin**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Hi @toocoolsachin thanks for the PR, could you make the file in the correct folder :smiley:

**Comment by toocoolsachin** [comment]
Hi @johnjacobkenny, sure will do that

**Comment by toocoolsachin** [comment]
Hi @johnjacobkenny, I have moved my .md file in the firstpr folder.

**Review by pranavgoel29 — APPROVED** [review]
@sarathkumar6 and @johnjacobkenny 
I have checked it's in the correct folder now, anyone with write permission can merge it.

**Pull request merged**
