### PR TITLE
Section 3 New web design updated

### PR DESCRIPTION
**Pull request by teckiegeek**
Section 3 has been updated and all the bootstrap code removed. 

image

### CODE REVIEW

**Comment by UnevenCoder** [comment]
Design's approved but why 3 imgs ?

**Comment by Akshay2996** [comment]
@teckiegeek Great job!! Please Resolve your merge conflict & one question here why are you using 3 img's?

**Comment by Akshay2996** [comment]
@teckiegeek I'm going to close this PR because @UnevenCoder also made the same changes & his PR got merged before yours.

**Comment by teckiegeek** [comment]
ok. that's fine.

**Pull request closed without merging**
