### PR TITLE
Renderer svelte

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
## Description
I added TOC creation, used prettier to fix indentation, another approachs are welcome

### CODE REVIEW

**Comment by proful** [comment]
@tolgaerdonmez conflicts?

**Comment by PuruVJ** [comment]
Dude, merge conflicts!

Otherwise, I'm trusting your word on this. I can't review all 31 files 😅. Can be approved

**Comment by tolgaerdonmez** [comment]
@proful @PuruVJ Yeah there are conflicts, I'm going to solve them no worries 😁

**Comment by PuruVJ** [comment]
Allright! Green flag from my side 👍

**Review by Akshay2996 — APPROVED** [review]

**Pull request merged**
