### PR TITLE
[USER ACTION] Create Fabio.md

### PR DESCRIPTION
**Pull request by lh536**
This is Fabio's first commit

### CODE REVIEW

**Comment by proful** [comment]
Congratulations on your first pr.

Small suggestions use lower case for file name.

**Comment by lh536** [comment]
Hi Proful! Thank you for your answer. I just rename Fabio.md to fabio.md... do I have to PR again?

**Comment by proful** [comment]
merged thanks

**Comment by johnjacobkenny** [comment]
> Hi Proful! Thank you for your answer. I just rename Fabio.md to fabio.md... do I have to PR again?

Hi @lh536. Once you create a PR, your fork is synced to the PR and any commits you add to your fork will automatically be visible in the PR page. Feels like magic, doesn't it 🥳

@piratelicorne this may be useful for FAQ

**Comment by pranavgoel29** [comment]
Ya that's a helpful FAQ as many were asking to make a new PR for the same sort of issue. 😄

**Pull request merged**
