### PR TITLE
Updated Landing Page Design

### PR DESCRIPTION
**Pull request by vasudeveloper001**
## Description
Changed the footer, header, and feature section colourings and styling.

## Attach Screenshot
image

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Review by Akshay2996 — APPROVED** [review]

**Review by madhusudanbabar — CHANGES_REQUESTED** [review]
can you make the email input field a bit smaller

**Comment by vasudeveloper001** [comment]
> can you make the email input field a bit smaller

I am working on that in another branch. This is concerned with footer, header, and feature section. I am working on index.js file and that requires modification in input field. So will push with that once done.

**Review by madhusudanbabar — APPROVED** [review]

**Comment by madhusudanbabar** [comment]
the image to the right of the **we are open community** is broken

**Review by madhusudanbabar — CHANGES_REQUESTED** [review]
the image to the right of **we are open community** is broken

**Comment by UnevenCoder** [comment]
Colors in the new design have been changed 😅
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A


Not being rude but for now we are following the design will try to minimise colors later on 😀

**Comment by UnevenCoder** [comment]
> the image to the right of **we are open community** is broken

That should be fixed in a new pr soon , with more changes

**Pull request closed without merging**
