### PR TITLE
Create ChiomaVera.md

### PR DESCRIPTION
**Pull request by chiomavera**

### CODE REVIEW

**Comment by arthurbuhl** [comment]
### Code Review Checklist

- [ ] For your first PR, please use all lower case for the file name.
- [ ] Please use `firstname.md` as file name. Replace `firstname` with your actual first name.
- [ ] In case there is already a file with same name, then use `firstname_lastname.md`.
- [x] Using `.md` file extension is a must.
- [x] Please add some basic bio about yourself in the first PR.

Please make changes to your PR to fulfill the first 3 points in the above checklist.

**Review by ad3rinto — CHANGES_REQUESTED** [review]
Hi Chioma, can you rename your file using all lower case?
cheers.

**Comment by chiomavera** [comment]
> Hi Chioma, can you rename your file using all lower case?
> cheers.

pls how do i do that

**Comment by ad3rinto** [comment]
@chiomavera  are you using VSCode? 
Go to the file in the file section, right-click on the file ( ChiomaVera.md) and rename it to "chiomavera.md.
Once done, push your changes.
Hope that helps.

**Comment by chiomavera** [comment]
> @chiomavera are you using VSCode?
> Go to the file in the file section, right-click on the file ( ChiomaVera.md) and rename it to "chiomavera.md.
> Once done, push your changes.
> Hope that helps.

ok,

**Comment by chiomavera** [comment]
> > @chiomavera are you using VSCode?
> > Go to the file in the file section, right-click on the file ( ChiomaVera.md) and rename it to "chiomavera.md.
> > Once done, push your changes.
> > Hope that helps.
> 
> ok,

have done that but the changes aren't reflecting

**Comment by ad3rinto** [comment]
To download all the changes and commits from main Repo.
git fetch upstream

The current branch will be updated to reflect the merge.
git merge upstream/main


Push the changes to own repository.
git push origin main

**Comment by ad3rinto** [comment]
[git - the simple guide - no deep shit!.pdf](https://github.com/twindle-co/twindle/files/5397951/git.-.the.simple.guide.-.no.deep.shit.pdf)
Have a read of this,

**Comment by UnevenCoder** [comment]
You deleted the file 😅

**Pull request closed without merging**
