### PR TITLE
Feature/epub generation

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
## Description
- Added epub generation ( needs design improvement. )
- Moved some files in renderer/pdf to renderer/

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by tolgaerdonmez** [comment]
@PuruVJ @proful I hope it is okay now

**Comment by PuruVJ** [comment]
this looks good. Can be merged

A question though. We have set up prettier config, and according to it, the indentations should only 2 spaces, but your code has 4 of those.

Can you check if you have the prettier config in the package.json? Send a screenshot.

**Comment by proful** [comment]
Good catch @PuruVJ

@tolgaerdonmez please format as per prettier configuration defined in package.json

**Comment by PuruVJ** [comment]
Here's the `.prettierrc` file. Paste it in twindle folder, so we can have equal formatting everywhere.

```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false,
  "printWidth": 100,
  "arrowParens": "always"
}

```

**Comment by proful** [comment]
@PuruVJ why this is needed?

We already have this configuration in package.json

@johnjacobkenny

**Comment by tolgaerdonmez** [comment]
> @PuruVJ why this is needed?
> 
> We already have this configuration in package.json
> 
> @johnjacobkenny

vscode don't recognize the package.json prettier config I believe

**Comment by proful** [comment]
It does for me.

You may have to try some settings

**Pull request merged**
