### PR TITLE
1st PR - Create puru.md with simple introduction

### PR DESCRIPTION
**Pull request by PuruVJ**

### CODE REVIEW

**Review by pranavgoel29 — APPROVED** [review]
It's ready to be merged.

**Comment by PuruVJ** [comment]
Do I open 2nd and 3rd PRs separately or is it fine to have the next 2 referenced here only?

**Review by pranavgoel29 — CHANGES_REQUESTED** [review]
Please make a seprate PR for TEAM.md file.

**Review by EYRAM565 — APPROVED** [review]

**Comment by EYRAM565** [comment]
conflicting files docs/TEAM.md @PuruVJ

**Comment by PuruVJ** [comment]
Hi I've resolved the conflict. Anything else I needa do?

**Comment by EYRAM565** [comment]
You can create with a header, footer or website

**Comment by UnevenCoder** [comment]
> Hi I've resolved the conflict. Anything else I needa do?

nothing bro all done

**Review by UnevenCoder — APPROVED** [review]
good to do

**Comment by PuruVJ** [comment]
I don't understand. Where is the code on this repo? Where's the backend? What's the structure to follow?

**Comment by UnevenCoder** [comment]
why closed
dude just wait
join the server , I will explain there

**Comment by shekhar10feb** [comment]
> 
> 
> I don't understand. Where is the code on this repo? Where's the backend? What's the structure to follow?

Please read this https://github.com/twindle-co/twindle/pull/371#issuecomment-712309373

**Comment by shekhar10feb** [comment]
https://github.com/twindle-co/twindle/blob/main/docs/FAQ.md please read this

**Comment by shekhar10feb** [comment]
Please read this https://github.com/twindle-co/twindle/blob/main/docs/FAQ.md

**Comment by sarathkumar6** [comment]
@PuruVJ  I see a couple of lines removed from the TEAM.md file.
Is that intended? 

- [ ] Verify the removal of a member info from TEAM.md

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
Why the names of the other team members deleted. The format for Team.md is broken. Please restore Team.md file.

puru.md file is good to go but TEAM.md you need to restore it.

**Pull request merged**
