### PR TITLE
Increase timeout for puppeteer

### LINKED ISSUE #689: puppetter bug not working timeout
image
`node . -i 1277933730078785537 -p`

[freelancing by tom hirst](https://twitter.com/tom_hirst/status/1277933730078785537)

### PR DESCRIPTION
**Pull request by PuruVJ**
Closes #689

### CODE REVIEW

**Comment by proful** [comment]
Give longer timeout 5min

**Comment by PuruVJ** [comment]
I've set the timout to 0, meaning there's no timeout(It's effectively Infinity)

**Comment by proful** [comment]
That's not good. Set 5 min timeout

**Comment by proful** [comment]
@PuruVJ so many changes?

**Comment by PuruVJ** [comment]
Just removed duplicate try catch. No big deal

**Pull request merged**
