### PR TITLE
Creating PDFs using Puppeteer

### PR DESCRIPTION
**Pull request by tolgaerdonmez**

### CODE REVIEW

**Review by johnjacobkenny — APPROVED** [review]
LGTM

**Comment by johnjacobkenny** [comment]
@tolgaerdonmez Thanks very much, this is excellent!!! :partying_face: 

Could you create a video, explaining what all you did, and how each of these modules works? Or it could be a session with others from our community also taking part, just ensuring that you record the session so others can watch at their convenience.

Also need one more reviewer, I don't know who to ask though :sweat_smile:

**Comment by tolgaerdonmez** [comment]
Thanks! 

I would really love to do a live session, but today I have lessons to attend at the same time as the sessions, but I can probably record a video 😊

**Review by michaelcosj — APPROVED** [review]

**Comment by tr0mbl3y** [comment]
@tolgaerdonmez can you please explain more about these "handlebar template"?

**Comment by tolgaerdonmez** [comment]
I'll create a video explaining the code, as soon as I can.
Handlebars templates is just a way of injecting data to html to create static pages. You can think it like thr template string in javascript.

**Comment by tolgaerdonmez** [comment]
@johnjacobkenny is this going to be merged, what are the plans

**Comment by proful** [comment]
2 approval and we can merge.

**Comment by proful** [comment]
Attach sample pdf screen shot please

**Comment by tolgaerdonmez** [comment]
@proful  Example files are actually available in the files I committed.
[Twindle.pdf](https://github.com/twindle-co/twindle/files/5407077/Twindle.pdf)

**Comment by tolgaerdonmez** [comment]
> You have 2 approval that's good.
> 
> Please fix the merge conflict and I will merge it immediately

I believe there is no more conflict/

**Comment by tolgaerdonmez** [comment]
Closes #357

**Comment by tolgaerdonmez** [comment]
Closes #351

**Comment by tolgaerdonmez** [comment]
@tr0mbl3y @johnjacobkenny 
I explained the code [here](https://youtu.be/llkkwRABN-s)

**Comment by johnjacobkenny** [comment]
@tolgaerdonmez love it!

@piratelicorne could you (or someone else) add this link in the resources docs

**Comment by tr0mbl3y** [comment]
@tolgaerdonmez  : well explained!thanks

**Comment by tolgaerdonmez** [comment]
> Attach sample pdf screen shot please 

@tr0mbl3y happy to help!

**Comment by piratelicorne** [comment]
video referenced in #399

**Pull request merged**
