### PR TITLE
Third PR: Included myself as an Intermediate developer in the Team file

### PR DESCRIPTION
**Pull request by Mira-Alf**
I have included myself as an intermediate developer in the Team file for the Third PR exercise. I continue to use VSCode Editor for the changes and git command line tool for pushing the changes to my cloned repository. Still learning things in Collaborative Git.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
@Mira-Alf you are one of the unfortunate (or fortunate? :partying_face: ) people to receive a merge conflict! To be honest, it probably isn't even your fault. One of the other PRs to the same file was probably merged sometime after you created your PR, thus resulting in a conflict.

**Comment by Mira-Alf** [comment]
Hey I merged the changes. Hope I have done it correctly.

**Comment by johnjacobkenny** [comment]
Since you are a little more experienced I will ask you to try once again with the merge request, but this time try using rebase, rather than merge. DM me on twitter if you have time to discuss about why.

**Comment by johnjacobkenny** [comment]
Hi @Mira-Alf i think there is still a conflict, try again please

**Comment by Mira-Alf** [comment]
@johnjacobkenny @proful Can you please merge it now? I think I resolved the conflicts.

**Comment by johnjacobkenny** [comment]
Yes @Mira-Alf now it's done! 🥳

**Pull request merged**
