### PR TITLE
Update CODE-REVIEW-CHECKLIST.MD

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Review by UnevenCoder — APPROVED** [review]
looks good to go

**Review by Akshay2996 — COMMENTED** [review]
- No need for spacing between the bullet points. 
- Structuring of the sentence in line 3 is a must.

Otherwise all is good👍

image

**Comment by piratelicorne** [comment]
@thunder-coding please fix your conflicts

**Comment by thunder-coding** [comment]
Currently not on desktop. Tommorow I will fix them

**Review by Akshay2996 — COMMENTED** [review]
Please resolve the merge conflict & then ask for review

**Review by PrasoonPratham — APPROVED** [review]

**Pull request closed without merging**
