### PR TITLE
header PR adewale

### PR DESCRIPTION
**Pull request by princehaybee**

### CODE REVIEW

**Review by Akshay2996 — COMMENTED** [review]
Hi @princehaybee  Just a minor change needed. In the Html file inside navbar Capitalize your About Us, & Features like Our Team written there.

Otherwise everything is perfect.

**Comment by proful** [comment]
Screen shot please?

**Comment by princehaybee** [comment]
@Akshay2996 thanks. I have edited it now.

**Comment by princehaybee** [comment]
@proful a screenshot has been added to the folder as well.

**Review by piratelicorne — APPROVED** [review]

**Comment by piratelicorne** [comment]
approved.

**Pull request merged**
