### PR TITLE
docs : improved about me file- swati rao --Second PR

### PR DESCRIPTION
**Pull request by SwatiRaoDataEnthusiast**
Accept my second PR

### CODE REVIEW

**Review by johnjacobkenny — APPROVED** [review]

**Comment by proful** [comment]
Ask in Twitter group by giving link to this pr for review and approval. 2 approval needed.

**Review by arthurbuhl — APPROVED** [review]

**Review by pranavgoel29 — APPROVED** [review]

**Comment by sarathkumar6** [comment]
Please resolve the merge conflict and remove the label when resolved @SwatiRaoDataEnthusiast Thanks.

**Comment by pranavgoel29** [comment]
@SwatiRaoDataEnthusiast Please pull the change from main repo to your forked repo once again and add table syntax to your name and description.

**Comment by SwatiRaoDataEnthusiast** [comment]
Okay I will do that

**Pull request closed without merging**
