### PR TITLE
Changes in epub.js

### PR DESCRIPTION
**Pull request by shekhar10feb**
## Description
Some changes in epub.js

## Attach Screenshot
epubjs

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Could you explain what all you have changed and how to run the code

**Comment by shekhar10feb** [comment]
> 
> 
> Could you explain what all you have changed and how to run the code

Instead of using tweets, created a format, used mock data for using twit-thread.json(will create) but I was stuck on how to create htmlContent and options and passing options variable as argument in new Epub as Tolga suggested.

**Comment by johnjacobkenny** [comment]
@tolgaerdonmez could you help out

**Comment by tolgaerdonmez** [comment]
> ons variable as argument in new Epub as Tolga sug

image

So here I added the generateEpub function and gave the tweets and outputPath created in the index.js

image

Here is the generateEpub function, which uses the newly created tweets

**Comment by shekhar10feb** [comment]
> 
> 
> > ons variable as argument in new Epub as Tolga sug
> 
> image
> 
> So here I added the generateEpub function and gave the tweets and outputPath created in the index.js
> 
> image
> 
> Here is the generateEpub function, which uses the newly created tweets

Thank you Kenny and Tolga

**Comment by johnjacobkenny** [comment]
@shekhar10feb I think the epub changes have been made by @tolgaerdonmez already? If yes, please close this and raise a PR just for the article you have written

**Comment by shekhar10feb** [comment]
> 
> 
> @shekhar10feb I think the epub changes have been made by @tolgaerdonmez already? If yes, please close this and raise a PR just for the article you have written

Ok

**Pull request closed without merging**
