### PR TITLE
Github repositories with learning resources added

### PR DESCRIPTION
**Pull request by PrasoonPratham**

### CODE REVIEW

**Review by pranavgoel29 — APPROVED** [review]
Thank you for adding these 😄

**Review by palashmon — APPROVED** [review]
Looks good to me. Ready to be merged :+1:

**Review by thunder-coding — APPROVED** [review]
Awesome 🔥🔥

Merge this fast @johnjacobkenny

**Review by arthurbuhl — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Got a conflict😅

**Review by sarathkumar6 — APPROVED** [review]

**Comment by proful** [comment]
@palashmon thanks for coming by 😊

**Comment by PrasoonPratham** [comment]
This was taken care off in another pr hence closed

**Pull request closed without merging**
