### PR TITLE
Create krypton.md

### PR DESCRIPTION
**Pull request by madhusudanbabar**

### CODE REVIEW

**Comment by proful** [comment]
Ask in Twitter group by giving link to this pr for review and approval. 2 approval needed.

**Review by pranavgoel29 — APPROVED** [review]
It's ready to be merged.

**Review by RafaelBatman55 — APPROVED** [review]

**Review by sarathkumar6 — APPROVED** [review]
Barring your physical address, you shared all the ways to reach out. lol
Good job @madhusudanbabar

**Comment by UnevenCoder** [comment]
@proful Pr waiting to be merged :)

**Comment by sarathkumar6** [comment]
@sammjainn Please review this PR if you have time

**Comment by sarathkumar6** [comment]
This one already has enough approvals. Merging this one.
@sammjainn nvm.

**Pull request merged**
