### PR TITLE
Updated CODE-REVIEW-CHECKLIST.md

### PR DESCRIPTION
**Pull request by pranavgoel29**
Added some more point to CODE-REVIEW-CHECKLIST.md file

### CODE REVIEW

**Review by PrasoonPratham — APPROVED** [review]
Approved

**Review by UnevenCoder — APPROVED** [review]
Good to go

**Comment by shekhar10feb** [comment]
It's good now

**Review by KiranDon — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
This was an awesome merge team! Good work I didn't even have to look at the code change! ❤️

**Pull request merged**
