### PR TITLE
Updated Readme links with markdown syntax

### PR DESCRIPTION
**Pull request by michaelcosj**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
This is not quite there yet, you can make it without any of the html tags like `a` or `img`

**Comment by michaelcosj** [comment]
I did try that but I couldn't find a standard way to resize the images to 50x50 in markdown syntax.
Should I use the full size images?

**Comment by johnjacobkenny** [comment]
Ohh okay got it. I'll merge this, but if you find another way just create another PR

**Comment by michaelcosj** [comment]
Will do!

**Comment by proful** [comment]
Good job @michaelcosj

**Pull request merged**
