### PR TITLE
My implementation of issues #288 and #301 - CLI application and Hello World PDF

### PR DESCRIPTION
**Pull request by michaelcosj**

### CODE REVIEW

**Comment by arthurbuhl** [comment]
I think we should have separation of concern and keep things simple. So, basically we should have like:

- `twindle-co/twindle` as our core app
- `twindle-co/twindle-cli` as our CLI app
	- The CLI app done in this PR
- `twindle-co/twindle-web` as our core website.
	- header.html, header.css
	- home_banner.html, home_banner.css
	- footer.html, footer.css
	- team_details.html, team_details.css
	- All our html files and assets should be here.

Just wanted to share my opinion. I will leave this up for other contributors for discussion.

**Comment by johnjacobkenny** [comment]
@arthurbuhl yes I agree we should move in that direction, but I think the idea for now is to keep things simple with one repo. As it evolves and matures we can move it out, what do you think?

**Comment by arthurbuhl** [comment]
Yes, I think the same. We should go with the way whichever is easier for everyone to understand and follow for now. But for getting a feel of real-world projects maybe be can look into above route in the future.

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
I can see to .gitignore files in your repo. No need to create two separate .gitignore files.

Create **one .gitignore file** in the **root directory** of the repository.

**Comment by arthurbuhl** [comment]
@Akshay2996: We already have one in the root here: https://github.com/twindle-co/twindle/blob/main/.gitignore

**Review by johnjacobkenny — APPROVED** [review]
Looks good @kingsley-einstein @tolgaerdonmez please share your thoughts

**Comment by michaelcosj** [comment]
Thanks @Akshay2996 
I'll remove them and edit the root gitignore

**Pull request merged**
