### PR TITLE
Footer color change

### PR DESCRIPTION
**Pull request by lh536**
## Description
Footer background color change to transparent and icons color to black.

## Attach Screenshot
image

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Review by Akshay2996 — APPROVED** [review]
@proful This is good to go 👍

**Comment by tr0mbl3y** [comment]
yes this is smooth!

**Comment by proful** [comment]
Great efforts @lh536 🎉🎉

**Comment by johnjacobkenny** [comment]
Good job @lh536

**Pull request merged**
