### PR TITLE
Added template and few minor changes to follow the template

### LINKED ISSUE #168: team.md styling better
Let's create a fixed format for people to follow

Name can be a link to github too , country , years of experience , and some special fact 👍 

lemme know what u think

### PR DESCRIPTION
**Pull request by UnevenCoder**
close #168

### CODE REVIEW

**Review by thunder-coding — CHANGES_REQUESTED** [review]
Fix the typo in 'tenplate' instead of 'template'

**Comment by UnevenCoder** [comment]
Done @thunder-coding

**Review by thunder-coding — APPROVED** [review]
👍👍

**Comment by nishanknavelkar** [comment]
looks good

**Review by nishanknavelkar — APPROVED** [review]

**Review by madhusudanbabar — APPROVED** [review]
Agree 👍

**Comment by proful** [comment]
Merge conflict.

**Comment by UnevenCoder** [comment]
@proful conflict resolved

**Comment by proful** [comment]
Again conflicts 😂

**Comment by sarathkumar6** [comment]
Please resolve the merge conflict and remove the label when resolved @UnevenCoder Thanks.

**Comment by UnevenCoder** [comment]
I just realised this is my pr 😂😂

**Comment by UnevenCoder** [comment]
Will do it tommorow on tab right now 😀

**Comment by johnjacobkenny** [comment]
This will break with the latest table structure, so please fix the conflict

**Comment by UnevenCoder** [comment]
I will close this and create a new pr later , this template is not needed as of now 👍

**Pull request closed without merging**
