### PR TITLE
updated README.md and created a file

### PR DESCRIPTION
**Pull request by Prateekatma**

### CODE REVIEW

**Comment by proful** [comment]
Looking great.

Ask in Twitter group or discord by giving link to this pr for review and approval. 2 approval needed.

**Comment by Prateekatma** [comment]
ok

**Review by Prateekcse — APPROVED** [review]
This is looking great✨

**Review by Sayantan-world — APPROVED** [review]

**Comment by proful** [comment]
please fix the merge conflicts

**Review by michaelcosj — APPROVED** [review]

**Comment by Prateekatma** [comment]
what should i do if resolve conflicts button is not showing?

**Comment by Neaz-Mahmood** [comment]
Please follow the steps shown in the link
https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts

**Pull request closed without merging**
