### PR TITLE
new pull 3rd pr

### PR DESCRIPTION
**Pull request by EdoriAtiri**

### CODE REVIEW

**Review by piratelicorne — APPROVED** [review]
Looks good, please ask for a second approval so it can be merged

**Comment by Neaz-Mahmood** [comment]
Please resolve the conflict

**Comment by shekhar10feb** [comment]
Capturedash

**Comment by shekhar10feb** [comment]
> 
> 
> Capturedash

Please remove the dash above Beginner

**Comment by EdoriAtiri** [comment]
> Looks good, please ask for a second approval so it can be merged

Thanks

**Review by EYRAM565 — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Still a conflict

**Comment by piratelicorne** [comment]
@EdoriAtiri please fix the conflicts and as soon as you do that, share the link in twitter so it can be merged. You already have 2 approvals.

**Comment by johnjacobkenny** [comment]
Yay 🥳

**Pull request merged**
