### PR TITLE
prettify conflict bot message

### PR DESCRIPTION
**Pull request by tr0mbl3y**

### CODE REVIEW

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
Hi @tr0mbl3y Instead of sending the user to a particular issue send them to the **Wiki Page** of [Resolving Merge Conflict](https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts)

**Review by piratelicorne — APPROVED** [review]

**Comment by piratelicorne** [comment]
Yes, I think it's a good idea to link to the Wiki Page, :octocat:

**Comment by tr0mbl3y** [comment]
sorry i didn't see that wiki page i will do it shortly thaanks @Akshay2996

**Review by Akshay2996 — APPROVED** [review]
It is good to go👍

**Pull request merged**
