### PR TITLE
epub generation added

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
### Flags configured & added:

- **-s / --send-email**: Boolean flag whether to send email or not
- **-e / --kindle-email**: Setting kindle email with this or **KINDLE_EMAIL** env variable.

### CODE REVIEW

**Comment by proful** [comment]
@tolgaerdonmez difficult to approve

So many changes?

**Comment by PuruVJ** [comment]
I have a more feature-rich functionality of same issue, plus better error messages #687

**Comment by PuruVJ** [comment]
Closing this, b'coz of the above comment, and also the fact the `misc` folder had been deleted before because of irrelevance, and this PR tries to introduce them again.

**Comment by tolgaerdonmez** [comment]
> We had deleted the `misc` folder cuz it was very irrelevant, but this PR introduces them again.

oups, I miss resolved the conflict then.

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez difficult to approve
> 
> So many changes?
> 
> It will cause big hassle for @PuruVJ and @Mira-Alf for resolving merge conflict.
> 
> As most of your changes relating to indentation, we can discuss separately whether to introduce prettier or not.
> 
> @johnjacobkenny 

we should now use prettier config, I acutally didnt changed a thousand lines of course.

**Comment by proful** [comment]
@tolgaerdonmez Kenny is refractoring the code and I have asked him to add prettier.

It should be done in couple of days

**Comment by tolgaerdonmez** [comment]
all right then 👍🏻

**Comment by PuruVJ** [comment]
@tolgaerdonmez I've done the changes you intended regarding Kindle email #687 and some more. Please review and if you're satisfied then close this PR

**Comment by tolgaerdonmez** [comment]
@proful @PuruVJ  I think I solved the big change problem

**Comment by tolgaerdonmez** [comment]
@proful I resolved the conflict by luck, could you merge :)

**Comment by proful** [comment]
it seems @PuruVJ fixed it. Please check with him if it is needed?

@PuruVJ pls confirm

**Comment by PuruVJ** [comment]
Those problems have already been fixed, and some more features have been added.

Permission to close your PR @tolgaerdonmez ?

**Comment by tolgaerdonmez** [comment]
@proful epub generation added

**Comment by proful** [comment]
Too much changes.

Can you create a new branch and a new PR please.

It will be difficult for merging.

**Review by PuruVJ — CHANGES_REQUESTED** [review]
This PR undoes lots of fixes I made throughout the day, like kindle email feature improvements and validations, error message cleanup, colored logging. Please pull in the latest changes, merge conflicts, then open a new PR instead, with much less files and commits, hopefully.

Thanks for the changes related to the epub stuff only. That looks good

**Comment by tolgaerdonmez** [comment]
@proful @PuruVJ how could I resolve the problem so that @proful can merge ?

**Comment by johnjacobkenny** [comment]
@tolgaerdonmez I think you may need to rebase on your fork to merge all into less commit, or some other direction if anyone else has

**Comment by PuruVJ** [comment]
Hi @tolgaerdonmez. We've made way too many changes now. Close this PR, make a new branch(e.g. epub-generation), then in that branch, pull everything from upstream main(`git pull https://github.com/twindle-co/twindle.git main`), resolve conflicts regarding the code you added, then push from that branch, and create a PR from that branch.

**Pull request closed without merging**
