### PR TITLE
Corrected dimensions of twitter icon in README.md

### PR DESCRIPTION
**Pull request by tusharkashyap63**
With new dimensions

### CODE REVIEW

**Comment by proful** [comment]
Request two ppl to review in Twitter group.

**Review by thunder-coding — APPROVED** [review]
Everything looks fine and better 👍

**Review by pranavgoel29 — APPROVED** [review]
Looks good 😄👍🏻

**Review by SunnyDev7 — COMMENTED** [review]
Perfect!!

**Pull request merged**
