### PR TITLE
Twitter API refactoring - focus on version 2.0 only

### PR DESCRIPTION
**Pull request by Mira-Alf**
## Description
Split the single script into multiple files

#Building a nodejs module from scripts that fetched tweet information from Twitter API
This project focuses on the version 2.0 of Twitter API
1. main.js - contains the starting function of this project getTweets(tweet_url)
2. index.js - shows an example tweet calling main.getTweets
3. Scripts to fetch tweets from other ways of Twitter API version 1.1 are available under misc folder
4. Sample twitter API responses in twitter_responses folder

**Input:**
*Inside the index.js file, replace the example tweet with a more recent tweet(in the last seven days) else no tweets will be obtained from Twitter
*Inside the utils/twitter-api-keys.js file, replace the AUTH_TOKEN_HERE with the bearer token obtained from Twitter
*index.js can be run using the command
    node index.js

**Output:**
Tweets obtained are written in output/twitter-api-response.json file

##Things left to do:

-Handling error scenarios -
    >Timeout Errors, 400/401 Authorization issues, Older than 7 days tweet issues
-Migrate to ES6 - code looks cluttered with require and module.exports syntax - would be better to use import and export keywords
-Need to check if newer tweets are available - to update the thread??

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by proful** [comment]
@Mira-Alf Create tasks for below

##Things left to do:

-Handling error scenarios -
>Timeout Errors, 400/401 Authorization issues, Older than 7 days tweet issues
-Migrate to ES6 - code looks cluttered with require and module.exports syntax - would be better to use import and export keywords
-Need to check if newer tweets are available - to update the thread??

So that other can pick it.

**Comment by Mira-Alf** [comment]
@proful creating those issues. Thanks!
This PR is related to #547

**Comment by johnjacobkenny** [comment]
> ## Description
> Split the single script into multiple files
> 
> #Building a nodejs module from scripts that fetched tweet information from Twitter API
> This project focuses on the version 2.0 of Twitter API
> 
> 1. main.js - contains the starting function of this project getTweets(tweet_url)
> 2. index.js - shows an example tweet calling main.getTweets
> 3. Scripts to fetch tweets from other ways of Twitter API version 1.1 are available under misc folder
> 4. Sample twitter API responses in twitter_responses folder
> 
> **Input:**
> *Inside the index.js file, replace the example tweet with a more recent tweet(in the last seven days) else no tweets will be obtained from Twitter
> *Inside the utils/twitter-api-keys.js file, replace the AUTH_TOKEN_HERE with the bearer token obtained from Twitter
> *index.js can be run using the command
> node index.js
> 
> **Output:**
> Tweets obtained are written in output/twitter-api-response.json file
> 
> ##Things left to do:
> 
> -Handling error scenarios -
> >Timeout Errors, 400/401 Authorization issues, Older than 7 days tweet issues
> -Migrate to ES6 - code looks cluttered with require and module.exports syntax - would be better to use import and export keywords
> -Need to check if newer tweets are available - to update the thread??
> 
> ## Attach Screenshot
> > Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

@Mira-Alf just a comment on how to format text in markdown, you may take a look at this guide https://guides.github.com/features/mastering-markdown/. And you can use the preview tab in github to preview the message
image

**Review by johnjacobkenny — APPROVED** [review]
LGTM as a first draft

**Comment by Mira-Alf** [comment]
Thanks @johnjacobkenny for the markdown link. I will keep that in mind.

**Comment by tr0mbl3y** [comment]
hey @Mira-Alf  are we handling paginating in the code as mentioned -->[here](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/paginate)
pic

**Comment by Mira-Alf** [comment]
@tr0mbl3y that's a great catch. V1.1 didn't have this problem because there was a request parameter count to limit the number of tweets. I will create an issue on this.. the threads I tested had less than 10 tweets.. so I need to test larger threads

**Review by praveen2896 — APPROVED** [review]
As a Beginner , it looks awesome . it seems like huge in terms of number of lines, but able to understand the code easily. Thanks @Mira-Alf

**Comment by praveen2896** [comment]
> As a Beginner , it looks awesome . it seems like huge in terms of number of lines, but able to understand the code easily. Thanks @Mira-Alf

I think once it is merged , will try in local  ,after that,  it is much easier for Beginners like me

**Review by tr0mbl3y — APPROVED** [review]

**Pull request merged**
