### PR TITLE
2nd and 3rd PR. Made change in "firstpr/kirandon.md" and Add myself as a beginner to TEAM using git CLI Locally.

### PR DESCRIPTION
**Pull request by KiranDon**

### CODE REVIEW

**Comment by proful** [comment]
please fix merge conflicts

**Comment by Sheetal777** [comment]
Hey  Click on the Resolve Conflict button, and try to rectify the problem. If the problem exists, attach a screenshot here, we would help you out.

**Comment by arthurbuhl** [comment]
Also, please rename the file to all lowercase. From `kiranDon.md` to `kiran_don.md`.

**Comment by Sheetal777** [comment]
Yes, now it looks good to be merged. Great work!

**Comment by KiranDon** [comment]
is everything alright now?

**Comment by Sheetal777** [comment]
Yes, cool!

**Pull request merged**
