### PR TITLE
Create TUSHAR.md

### PR DESCRIPTION
**Pull request by tusharkandpal**
First-Ever PR

### CODE REVIEW

**Review by sarathkumar6 — APPROVED** [review]
Congrats on your first PR, Tushar

**Comment by johnjacobkenny** [comment]
Thanks @tusharkandpal :partying_face:

**Comment by pranavgoel29** [comment]
#75 Please check this. @tusharkandpal, @johnjacobkenny, @sarathkumar6

**Comment by proful** [comment]
Congratulations on your first pr

**Pull request merged**
