### PR TITLE
Create wamuyuwanjohi

### PR DESCRIPTION
**Pull request by WanjohiWanjohi**
Adding Wamuyu md

### CODE REVIEW

**Review by arthurbuhl — COMMENTED** [review]
Hi Wamuyu,

I think you have forgotten to add `.md` file extension in the end. Please rename the file and commit again. 

Thanks!

**Review by nishanknavelkar — CHANGES_REQUESTED** [review]
rename `wamuyuwanjohi` to `wamuyuwanjohi.md`

**Review by piratelicorne — COMMENTED** [review]
change the extension to ".md" so it can be approved, please

**Comment by Na-ilah** [comment]
This is good to merge now

**Comment by arthurbuhl** [comment]
@Na-ilah: Not sure how is it "good to merge now", as the file is still missing the extension to ".md" and there are no new changes even after reviews by me, @nishanknavelkar and @piratelicorne also.

@proful: Please revert this merge for now and add a proper label to it or close this PR for now.

**Comment by proful** [comment]
OK reverting. Trying to clear up the backlog.

I thought review comments addressed.

**Comment by arthurbuhl** [comment]
Its ok. It just that now I have to review the reviews also sometimes along with PR, as few are taking it lightly. Hope this scenario with slowly improve as we move forward.

**Pull request merged**
