### PR TITLE
added myself in team.md

### PR DESCRIPTION
**Pull request by NahuelAlfano**

### CODE REVIEW

**Comment by Sheetal777** [comment]
@johnjacobkenny This one looks good to get merged.

**Review by tusharkandpal — APPROVED** [review]
Good to go 👍

**Comment by tusharkandpal** [comment]
@Sheetal777 you can approve changes for the file just by selecting approve instead of comment.. This will help

**Comment by Sheetal777** [comment]
@tusharkandpal Do we need to have access for that? I mean, can anyone approve changes?

**Comment by johnjacobkenny** [comment]
Anyone can add review comments and approval or rejection

**Comment by sarathkumar6** [comment]
@Sheetal777 Anyone can review and approve PRs. Please feel free to jump in and review.

**Comment by Sheetal777** [comment]
@tusharkandpal @johnjacobkenny @sarathkumar6 Thanks guys, I have been only commenting on many PRs till now without realising :P

**Pull request merged**
