### PR TITLE
Contributors Section Twindle Website

### PR DESCRIPTION
**Pull request by UnevenCoder**
Figma design
image
Coded Design
image

Automation will be done later :)

### CODE REVIEW

**Comment by UnevenCoder** [comment]
@vasu001 @JoelVinayKumar  requesting your review

**Comment by JoelVinayKumar** [comment]
Just reduce one profile per row.6 profiles per row should be fine.
And, increase the font size by 5-10px more

**Comment by Akshay2996** [comment]
@UnevenCoder Great work like the design👍 Keep up the good work loving it😍

**Comment by RafaelBatman55** [comment]
I agree with you @Akshay2996

**Comment by UnevenCoder** [comment]
I agree with you @Akshay2996  that sounds better tbh

**Comment by UnevenCoder** [comment]
I will close this PR then ;)

**Comment by JoelVinayKumar** [comment]
@Akshay2996 I renamed teams as "contributors" as it makes more sense

**Comment by UnevenCoder** [comment]
Definitely thanks for the update :)

**Pull request closed without merging**
