### PR TITLE
Mock responses

### PR DESCRIPTION
**Pull request by PuruVJ**
## Description
Some mock responses, latest.

@Mira-Alf Give me some more tweet IDs that you want mocks of. Not before than 7 days. When we have enough we can have it closed.

### CODE REVIEW

**Comment by Mira-Alf** [comment]
Just one file is enough we simply need to modify the file path to point to this latest file. The mock file needs to have the updated json structure.

**Comment by proful** [comment]
@PuruVJ please discuss with @Mira-Alf 
I will merge after @Mira-Alf approves here 😊

**Comment by PuruVJ** [comment]
The 2 files I made have enough content that this PR can be merged, but will the data structure will need to be updated when I'm done with showing embedded tweets

**Comment by Mira-Alf** [comment]
Okay sounds good. I will take care of updating the mock file.

**Review by Mira-Alf — APPROVED** [review]

**Pull request merged**
