### PR TITLE
Create design-guide-for-good-logo.md

### PR DESCRIPTION
**Pull request by aesthytik**
It is a small guide for beginners who are designing a logo. Here are my two cents for a good logo design, having designed logos for some of my clients in past. 

It is not mandatory to follow each point but keeping in mind these will be helpful.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Nice @aesthytik! Looking forward to working with you ❤️

**Review by johnjacobkenny — APPROVED** [review]

**Comment by aesthytik** [comment]
> Nice @aesthytik! Looking forward to working with you ❤️

thanks for the approval kenny. Love how you engage with the twindle community 👍 😄 🙌🏼

**Comment by ni3-kdm** [comment]
Nice Info related to logo design 👍

**Comment by proful** [comment]
Very good @aesthytik

**Review by ni3-kdm — APPROVED** [review]

**Pull request merged**
