### PR TITLE
Added the urls and the icons in the readme as requested by @proful

### LINKED ISSUE #118: Add Youtube, twitter Link in readme with icon
Someone take the task and update the readme file with icon

Github: https://github.com/twindle-co/twindle
Twindle YT:		https://www.youtube.com/channel/UCKxUmbHq5P5pd5IyUiZ8MHA
Daily Standup Playlist:
https://www.youtube.com/watch?v=mveHORtiKx8&list=PLJ6Y8JfXAV--l82_UnUi4w7WEaYJhJFRQ

Twitter: https://twitter.com/twindleco

### PR DESCRIPTION
**Pull request by UnevenCoder**
close #118

### CODE REVIEW

**Comment by proful** [comment]
Screen shot?

How it looks

**Comment by UnevenCoder** [comment]
image

**Comment by proful** [comment]
Daily call Playlist

Looks good

Fix

**Comment by arthurbuhl** [comment]
Here is a small trick. If you use a supported keyword in the pull request's description like:

```
close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved
```

**Example**: Closes #118

Then the linked issue will be auto closed when you merge the commit into the default branch.

For more info:

- [Linking a pull request to an issue](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [Automatically closing issue from pull request in GitHub](https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github).

**Comment by UnevenCoder** [comment]
done @proful

**Pull request merged**
