### PR TITLE
Add aravind.md for my first PR

### PR DESCRIPTION
**Pull request by aravindsivasailam**
- Giving an introduction to myself to be a contributor for this project.

### CODE REVIEW

**Comment by proful** [comment]
Welcome @aravindsivasailam

**Comment by Mira-Alf** [comment]
Hey Aravind, Welcome! This PR can be merged.

**Review by Mira-Alf — APPROVED** [review]

**Review by Mira-Alf — APPROVED** [review]

**Review by ni3-kdm — APPROVED** [review]
PR Looks fine!

**Comment by johnjacobkenny** [comment]
@aravindesri Welcome Aravind! Loved your discussion video on the twindle channel too :heart:

**Pull request merged**
