### PR TITLE
My 4th PR

### PR DESCRIPTION
**Pull request by shekhar10feb**
## Description
Attached a photo in TEAM.md

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by shekhar10feb** [comment]
scr1
 Screenshot

**Comment by shekhar10feb** [comment]
scr2

**Review by KiranDon — APPROVED** [review]

**Comment by KiranDon** [comment]
👍

**Review by piratelicorne — APPROVED** [review]
Looking good!

**Review by ni3-kdm — APPROVED** [review]
PR looks fine!

@shekhar10feb
- You can add description and screenshots in the description area 👇
image

**Comment by shekhar10feb** [comment]
> 
> 
> PR looks fine!
> 
> @shekhar10feb
> 
>     * You can add description and screenshots in the description area point_down
>       image



> 
> 
> PR looks fine!
> 
> @shekhar10feb
> 
>     * You can add description and screenshots in the description area point_down
>       image

I will do it....thank you

**Pull request merged**
