### PR TITLE
Added my github photo in a particular format

### PR DESCRIPTION
**Pull request by Akshay2996**
## Purpose

- ...

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type

What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## How to Test

- Get the code

```
git clone https://github.com/twindle-co/twindle.git
cd twindle
git checkout [branch-name]
```

### What to Check

Verify that the following are valid

- ...

### CODE REVIEW

**Comment by Akshay2996** [comment]
We should all follow the photo addition convention mentioned in the [issue](https://github.com/twindle-co/twindle/issues/492)

@proful @pranavgoel29 @johnjacobkenny Review this & see if we can follow the same convention as mentioned in this [issue](https://github.com/twindle-co/twindle/issues/492)?

If you preview this in your **Vscode** it looks like this:
image

If you preview on **Github** it looks like this:
image

**Comment by pranavgoel29** [comment]
> We should all follow the photo addition convention mentioned in the [issue](https://github.com/twindle-co/twindle/issues/492)
> 
> @proful @pranavgoel29 @johnjacobkenny Review this & see if we can follow the same convention as mentioned in this [issue](https://github.com/twindle-co/twindle/issues/492)?
> 
> If you preview this in your **Vscode** it looks like this:
> image
> 
> If you preview on **Github** it looks like this:
> image

Ya I think we should follow this one as it will be haslefree to some point and if someone is not having their Github profile photo then they can upload and do from the another method.

**Comment by Akshay2996** [comment]
@proful @johnjacobkenny @sarathkumar6  need your advice on this PR?

**Comment by johnjacobkenny** [comment]
Hey I think if you look at the same file how Proful and I have added our profile, it is same idea, looks cleaner too :smiley: You may try that way

**Comment by Akshay2996** [comment]
Fixed the format of the Table for Omolog. Previously TEAM.md table for internediate was breaking. All the things are done & corrected.

**Comment by Akshay2996** [comment]
@johnjacobkenny @proful  review this & merge it if this is good to go

**Review by johnjacobkenny — APPROVED** [review]

**Pull request merged**
