### PR TITLE
YouTube link added

### LINKED ISSUE #209: Video tutorial for second pull request
[](http://www.youtube.com/watch?v=cBigFcoAXZg "")
How to do Second PR with git bash

### PR DESCRIPTION
**Pull request by naveenkala**
Closes #209

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
@naveenkala Youtube link doesn't need to be `m.youtube.com` right

**Comment by naveenkala** [comment]
> @naveenkala Youtube link doesn't need to be `m.youtube.com` right

Link changed :)

**Review by Akshay2996 — APPROVED** [review]
Good to be approved👍

**Review by shekhar10feb — APPROVED** [review]
Approved

**Pull request merged**
