### PR TITLE
kingsley_victor

### PR DESCRIPTION
**Pull request by kingsley-einstein**

### CODE REVIEW

**Review by EYRAM565 — COMMENTED** [review]
your first PR should be an empty one and the second PR should be few lines about yourself and the third one will be to update your local repo and state your level of experience whether you are a beginner, intermediate or mentor in the TEAM.md folder.

**Comment by kingsley-einstein** [comment]
> your first PR should be an empty one and the second PR should be few lines about yourself and the third one will be to update your local repo and state your level of experience whether you are a beginner, intermediate or mentor in the TEAM.md folder.

Fixed accordingly!

**Comment by johnjacobkenny** [comment]
Thanks @EYRAM565 for the review. I think I'll let this pass since @kingsley-einstein is pretty experienced with these

**Comment by johnjacobkenny** [comment]
@kingsley-einstein please try the 3rd PR after cloning to your laptop if you haven't already

**Comment by EYRAM565** [comment]
okay Kenny.

**Comment by johnjacobkenny** [comment]
Oh hehe 🤣

**Comment by EYRAM565** [comment]
lol

**Pull request merged**
