### PR TITLE
twindle header

### PR DESCRIPTION
**Pull request by Mar-code**

### CODE REVIEW

**Comment by Mar-code** [comment]
My header design

**Comment by proful** [comment]
@Mar-code screen shot please?

**Comment by Mar-code** [comment]
Screenshot (12)

**Comment by Mar-code** [comment]
am working on a footer and a more interactive page with javascript

**Comment by proful** [comment]
Wow looks great.

I like the little robot.

Ask in Twitter group or discord by giving link to this pr for review and approval. 2 approval needed.

**Comment by stamenkovic-dev** [comment]
It looks really great 
I have something similar on my QNAP... it waves when you hover the image
image

**Review by wgaurav — APPROVED** [review]
Wow

**Review by sarathkumar6 — APPROVED** [review]

**Pull request merged**
