### PR TITLE
Merge pull request #1 from twindle-co/main

### PR DESCRIPTION
**Pull request by tr0mbl3y**
update

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Not sure what happened here, could you explain what you're trying

**Comment by tr0mbl3y** [comment]
sorry i have no idea! i just changed the setting to make "test" as my "main" branch and just tried to update it

**Comment by tr0mbl3y** [comment]
how do i retract this change?

**Comment by Rakesh-4** [comment]
> how do i retract this change?

you can close the pull request and if you want to delete the test branch locally you can do this `git branch -d test` but make sure you are not on the branch currently . `git checkout master` or `git switch master` will change the branch to master.  And then you can delete it.

**Comment by johnjacobkenny** [comment]
I think it's called "main" nowadays

**Comment by Rakesh-4** [comment]
Yeah. old habits won't d!e easily lol

**Comment by johnjacobkenny** [comment]
Lol yes 😜

**Comment by tr0mbl3y** [comment]
got it, i will delete it

**Comment by UnevenCoder** [comment]
Close the pr too

**Pull request closed without merging**
