### PR TITLE
[USER ACTION] therealjimoh.md

### PR DESCRIPTION
**Pull request by therealJimoh**

### CODE REVIEW

**Comment by proful** [comment]
Congratulations on your first pr. Use all file in lower case

**Review by pranavgoel29 — APPROVED** [review]

**Comment by pranavgoel29** [comment]
sorry done by mistake.

**Comment by proful** [comment]
No problem. Thanks for reviewing the pr. It's really helpful to me.

**Comment by sarathkumar6** [comment]
Looks good to me, the file name is changed to lowercase.

**Review by sarathkumar6 — APPROVED** [review]

**Review by sarathkumar6 — CHANGES_REQUESTED** [review]
Just notices. The letter J is caps on the file name. Please update that. Thanks.

**Comment by therealJimoh** [comment]
The file name are all on lower case. The letter J is in my username and not file name.

**Review by therealJimoh — COMMENTED** [review]
I just changed the file name to all lower case.

**Review by pranavgoel29 — APPROVED** [review]
Now file name is changed, its ready to merge 😄

**Comment by johnjacobkenny** [comment]
@sarathkumar6 may please sign off on this and merge it

**Pull request merged**
