### PR TITLE
Third pr MumbiGachomba04

### PR DESCRIPTION
**Pull request by MumbiGachomba04**

### CODE REVIEW

**Review by UnevenCoder — APPROVED** [review]
Looks great :)

**Review by thunder-coding — APPROVED** [review]
👍

**Review by EYRAM565 — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Merge conflict, @MumbiGachomba04 please update

**Comment by johnjacobkenny** [comment]
You will need to do that again, because someone else had updated the project in between. 😅

**Comment by MumbiGachomba04** [comment]
How about now?

**Comment by johnjacobkenny** [comment]
Yep! Its done 
Thanks team

**Pull request merged**
