### PR TITLE
The icon entry for team.md (There are extra commits also showing, how to fix it? Somebody help)

### PR DESCRIPTION
**Pull request by Sheetal777**
There are a lot of commits showing here, including those that I merged earlier to make even with base repo. Is this a problem or it can be merged?

### CODE REVIEW

**Comment by proful** [comment]
Welcome back @Sheetal777 
If you create a new branch and make the changes it will be clean.

**Comment by Sheetal777** [comment]
@proful  Yes thank you, I will do the same :)

**Comment by Sheetal777** [comment]
Can this be closed now?

**Comment by proful** [comment]
please close this

**Comment by johnjacobkenny** [comment]
Curious to see how you fix this multiple commits issue, if you get time, please add a wiki entry outlining the correct process. I too faced the same issue.

**Comment by Sheetal777** [comment]
Yes @johnjacobkenny after some googling I found something out called Rebase to squash multiple commits. And that's a great idea thankyou, I will document it for sure.

**Pull request closed without merging**
