### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Lyks012**
fixed a small typo

### CODE REVIEW

**Review by sarathkumar6 — APPROVED** [review]

**Review by sarathkumar6 — CHANGES_REQUESTED** [review]
Resolve merge conflict. Thanks.

**Comment by Lyks012** [comment]
> Resolve merge conflict. Thanks.

**Comment by proful** [comment]
Looks like he fixed the merge conflict

**Comment by Lyks012** [comment]
Yes I did. I was trying to figure out how to fix it and I forgot to tell him when i did. Sorry for that !

**Pull request merged**
