### PR TITLE
Updating TEAM.md

### PR DESCRIPTION
**Pull request by pranavgoel29**
Testing how you can make PR from inside of vscode using GUI interface.

### CODE REVIEW

**Comment by pranavgoel29** [comment]
@PrasoonPratham and @johnjacobkenny or someone else can review it.

**Comment by proful** [comment]
Ask in Twitter group by giving link to this pr for review and approval.

**Review by johnjacobkenny — APPROVED** [review]
LGTM

**Review by thunder-coding — APPROVED** [review]
👍👍

**Comment by pranavgoel29** [comment]
Thank you for approval

**Comment by proful** [comment]
Why you remove few entries?

**Comment by pranavgoel29** [comment]
I have not removed any entry maybe some pull request were merged after I have submitted my that can be the reason 😅

**Comment by pranavgoel29** [comment]
@proful now I have pulled the changes from main repo to my forked repo the files should be ok now.

**Review by johnjacobkenny — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
The changes are fine, but there seems to be a merge conflict! @pranavgoel29

**Comment by johnjacobkenny** [comment]
After you create a PR, if someone else's PR on the same file is merged in, then your PR becomes stale. It's rather unfortunate and a double work for you 😅

**Comment by johnjacobkenny** [comment]
Yess! Finally it is merged ❤️🥳

**Comment by pranavgoel29** [comment]
Thank you 😄
Finally!

**Pull request merged**
