### PR TITLE
Added a visitor's count badge

### PR DESCRIPTION
**Pull request by thunder-coding**
Inspired by @Abiolagbode's First PR.

### CODE REVIEW

**Comment by proful** [comment]
Can you please paste screen shot

**Comment by arthurbuhl** [comment]
It looks something like this..

[Open Source Love](https://github.com/firstcontributions/open-source-badges) [Pull Requests Welcome](http://makeapullrequest.com) image

**Comment by proful** [comment]
Looking good

**Comment by thunder-coding** [comment]
Earlier it had no conflicts, need to fork again :(

**Pull request closed without merging**
