### PR TITLE
first pr sravan

### PR DESCRIPTION
**Pull request by jsdevsravan**

### CODE REVIEW

**Review by madhusudanbabar — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
@jsdevsravan I think you need to move one of the files into the correct folder?

**Review by madhusudanbabar — CHANGES_REQUESTED** [review]
The file should be in `firstpr` folder

**Comment by jsdevsravan** [comment]
@johnjacobkenny  How to move the file?

**Comment by jsdevsravan** [comment]
@madhusudanbabar  how to move the file?

**Comment by Rakesh-4** [comment]
> @madhusudanbabar how to move the file?

open the editor and move the file inside firstpr folder and git will automatically track everything. Add and commit changes

**Comment by jsdevsravan** [comment]
@Rakesh-4  you mean editors like VS code? if so how to get the the files to editor?...Can we move the file  in this site directly and rasie pull request?

**Comment by Rakesh-4** [comment]
> @Rakesh-4 you mean editors like VS code? if so how to get the the files to editor?...Can we move the file in this site directly and rasie pull request?


> @Rakesh-4 you mean editors like VS code? if so how to get the the files to editor?...Can we move the file in this site directly and rasie pull request?

Are you on discord?

**Comment by jsdevsravan** [comment]
@Rakesh-4 No..How to add to that?

**Comment by jsdevsravan** [comment]
@Rakesh-4  iam creating account on discord..

**Comment by jsdevsravan** [comment]
@Rakesh-4  sravanjsdev is my discord id..can you ping/call on it

**Comment by madhusudanbabar** [comment]
> @madhusudanbabar how to move the file?

Actually, this is your first PR, so you are supposed to do it from github website only but in order to resolve this issue, you'll need to use cli or github desktop app, but anyways, i guess @Rakesh-4 have told you that already.

**Comment by proful** [comment]
@jsdevsravan use twindle discord server. It will be easy for you.

**Comment by jsdevsravan** [comment]
@madhusudanbabar  since iam a bignner,i found it confusing to raise first pr from github itself, let alone using CLI or GITHUB app...can anyone please jump to my rescue to help me on screen share?

**Comment by jsdevsravan** [comment]
@proful Can you please provide me the link

**Comment by johnjacobkenny** [comment]
@jsdevsravan did someone help you out? If you need help please DM me

**Comment by jsdevsravan** [comment]
@johnjacobkenny  Hi Kenny.. I will DM you on twitter

**Comment by UnevenCoder** [comment]
Waiting for changes 😅

**Review by johnjacobkenny — APPROVED** [review]

**Pull request merged**
