### PR TITLE
updated TEAM.md

### PR DESCRIPTION
**Pull request by ululi**

### CODE REVIEW

**Review by sammjainn — APPROVED** [review]

**Review by Akshay2996 — APPROVED** [review]
Good to go

**Comment by piratelicorne** [comment]
@ululi , please fix the conflicts and after it, send the link in the twitter group, because it already has 2 approvals.

**Comment by ululi** [comment]
resolved  merge conflicts.

**Comment by johnjacobkenny** [comment]
Done! Thanks team 🥳

**Pull request merged**
