### PR TITLE
Syncing my repo

### PR DESCRIPTION
**Pull request by pranavgoel29**
## Description
Just synced my repo with the main one and Added the fix to my file which is suggested in PR #663

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by proful** [comment]
no need to upload playground/cli/cli-epub/test.epub

**Comment by proful** [comment]
why this PR?

**Comment by RafaelBatman55** [comment]
Maybe @pranavgoel29 just wants to sync his own forked repository, but when he tried to do that, he chose the original one.

I already made this mistake this week.

**Comment by proful** [comment]
@pranavgoel29 please close this PR

**Pull request closed without merging**
