### PR TITLE
First PR - maria_rivera.md

### PR DESCRIPTION
**Pull request by GorettiRivera**

### CODE REVIEW

**Comment by UnevenCoder** [comment]
Add some more details tho but that's your opinion

**Review by UnevenCoder — APPROVED** [review]
All good

**Comment by GorettiRivera** [comment]
> Add some more details tho but that's your opinion

That's the purpose of second PR?

**Comment by johnjacobkenny** [comment]
Congrats @GorettiRivera 🥳

Thanks Ameen 🙂

**Pull request merged**
