### PR TITLE
Removed the GitHub icon

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
@thunder-coding curious did you use laptop or GitHub to create the commit

**Comment by thunder-coding** [comment]
GitHub Web

**Comment by proful** [comment]
Ask in Twitter group by giving link to this pr for review and approval. 2 approval needed.

**Review by tusharkashyap63 — APPROVED** [review]
Yeah, makes a lot more sense now.

**Comment by krishnadevz** [comment]
> 
> 
> @thunder-coding curious did you use laptop or GitHub to create the commit

he is asking did you use Git-bash from the local system or used the GitHub website/web-app

**Review by krishnadevz — APPROVED** [review]

**Comment by thunder-coding** [comment]
GitHub Website

**Comment by johnjacobkenny** [comment]
> GitHub Web
> 
> 
> 
> Any issues??

Nope just asked

**Comment by thunder-coding** [comment]
2 reviews done ✅

Waiting for the PR to get merged.

**Comment by johnjacobkenny** [comment]
@proful not getting the option to merge even though two have signed off on this

**Review by sarathkumar6 — APPROVED** [review]

**Pull request merged**
