### PR TITLE
firstPR

### PR DESCRIPTION
**Pull request by lokunade**

### CODE REVIEW

**Review by EYRAM565 — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Thanks @lokunade @EYRAM565

**Comment by EYRAM565** [comment]
you are welcome Kenny.

**Comment by lokunade** [comment]
Thank you @EYRAM565 but what is the next step?

**Comment by EYRAM565** [comment]
You need to create your second PR from your local machine by cloning your the forked repo and saying few things about yourself in   the doc folder. Then create your PR again from your local machine this time you have update your forked repo from the main repo. After that you state your experience whether you are a beginner ,intermediate or mentor in the TEAM.md file in doc folder.
if you having any difficulties in creating the second and third PR  click this https://www.youtube.com/channel/UCKxUmbHq5P5pd5IyUiZ8MHA to help .

**Comment by lokunade** [comment]
I have created the second pull request and it has been merged. thank you
What is next after that?

**Comment by EYRAM565** [comment]
Create your third PR again from your local machine this time you have update your forked repo from the main repo. After that you state your experience whether you are a beginner ,intermediate or mentor in the TEAM.md file in doc folder. if you having any difficulties in creating the  third PR click this https://www.youtube.com/channel/UCKxUmbHq5P5pd5IyUiZ8MHA to help .

**Pull request merged**
