### PR TITLE
Update firstpr folder instructions

### PR DESCRIPTION
**Pull request by RafaelBatman55**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Needs review

**Review by nishanknavelkar — APPROVED** [review]

**Review by UnevenCoder — APPROVED** [review]
Looks good

**Comment by UnevenCoder** [comment]
@johnjacobkenny  ready to merge 😉

**Review by ad3rinto — APPROVED** [review]
Ok

**Comment by johnjacobkenny** [comment]
Thanks guys

**Comment by RafaelBatman55** [comment]
Thank you guys!

**Pull request merged**
