### PR TITLE
first pr ~ blessing

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**

### CODE REVIEW

**Comment by proful** [comment]
Use lower case for file name

**Comment by proful** [comment]
@Olaleye-Blessing close this pr if you are not planning to fix it.

**Review by nishanknavelkar — CHANGES_REQUESTED** [review]
Rename the title from `Blessing.md` to `blessing.md` (first letter lower case) as per the naming convention [https://github.com/twindle-co/twindle/blob/main/docs/NAMING-CONVENTIONS.md](url)

**Review by nishanknavelkar — APPROVED** [review]
Looks good, Congrats on your first PR,
You need one more Approval .
You can find people online and ask for their help on discord
https://discord.gg/2hyQcsT

**Review by UnevenCoder — APPROVED** [review]
**Congrats ready to be merged**

**Review by pranavgoel29 — APPROVED** [review]
Ready to be merged

**Review by piratelicorne — APPROVED** [review]

**Review by nishanknavelkar — APPROVED** [review]

**Comment by pranavgoel29** [comment]
@johnjacobkenny can you merge this one. I think it is missed.

**Comment by johnjacobkenny** [comment]
Done! Thanks team 🥳

**Pull request merged**
