### PR TITLE
Adding my details

### PR DESCRIPTION
**Pull request by ad3rinto**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
There is a conflict!

**Review by ad3rinto — COMMENTED** [review]
looks good

**Comment by ad3rinto** [comment]
@johnjacobkenny  This is the message "This branch has no conflicts with the base branch"

**Comment by proful** [comment]
2 approval?

**Comment by ad3rinto** [comment]
@proful Please what else must I do to get this approved? And merged. Thanks

**Comment by proful** [comment]
Ask in Twitter group or discord by giving link to this pr for review and approval. 2 approval needed.

**Review by sarathkumar6 — APPROVED** [review]

**Comment by UnevenCoder** [comment]
Also msg in the discord server might geg some ppl

**Comment by UnevenCoder** [comment]
Congrats :)

**Comment by ad3rinto** [comment]
Thank you 😁

**Pull request merged**
