### PR TITLE
Why users should consider Twindle as first choice to read through Twitter thread

### PR DESCRIPTION
**Pull request by sarathkumar6**
Explains the pain point
Existing solutions
Limitations of threaderapp
How Twindle will help user convert Twitter threads -> pdf/ePub and access offline

### CODE REVIEW

**Comment by proful** [comment]
Thank you very much Sarthak!

**Comment by johnjacobkenny** [comment]
> Thank you very much Sarthak!

Sarthak or Sarath I'm confused (and I'm on mobile 😂)

**Comment by proful** [comment]
Luckily edit button is there in github unlike Twitter

**Review by johnjacobkenny — COMMENTED** [review]
LGTM

**Pull request merged**
