### PR TITLE
Added pranavgoel29.md and Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pranavgoel29**
Just added my info.

Added one point to how to contribute portion in CONTRUTING.md file

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Hi @pranavgoel29 could you separate these into two PRs :smiley:

**Comment by pranavgoel29** [comment]
I was having some problem in doing that, it would be very helpful if can you guide me.

**Comment by johnjacobkenny** [comment]
Hi @pranavgoel29 did you figure this out?

**Comment by pranavgoel29** [comment]
No I am going to make a new PR

**Comment by johnjacobkenny** [comment]
Great!

**Pull request closed without merging**
