### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by Prateekatma**
just ordered some unordered ones

### CODE REVIEW

**Review by EYRAM565 — APPROVED** [review]

**Comment by Rakesh-4** [comment]
Unfortunately, it broke the format because you used both ordered and unordered together.

**Review by UnevenCoder — CHANGES_REQUESTED** [review]
Using both ordered and ordered 
1. - hey
1. - hey

just do 
1. hey
1. hey
instead of 
- hey
- hey

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
It breaking the format because your are using both the ordered & unordered list as mentioned by other developers above. Please change this & submit a new PR.

**Comment by Prateekatma** [comment]
hmm got it

**Comment by Prateekatma** [comment]
I will update it in good way

**Pull request closed without merging**
