### PR TITLE
Third PR

### PR DESCRIPTION
**Pull request by nishanknavelkar**
Updated my info to Team.md

### CODE REVIEW

**Comment by proful** [comment]
Ask in Twitter group or discord by giving link to this pr for review and approval. 2 approval needed.

**Review by EYRAM565 — APPROVED** [review]

**Review by EYRAM565 — APPROVED** [review]

**Review by UnevenCoder — APPROVED** [review]
job well done

**Comment by sarathkumar6** [comment]
Please resolve the merge conflict and tag the reviewers in the comments for re-review. Thanks. @nishanknavelkar

**Comment by EYRAM565** [comment]
conflicting files it must resolve before this repo can merge

**Comment by pranavgoel29** [comment]
@nishanknavelkar you have to pull the changes from the main repo to your forked repo to solve the conflict.

**Comment by nishanknavelkar** [comment]
@EYRAM565 @pranavgoel29 @sarathkumar6 , kindly check if this has sorted out the conflicts

**Pull request merged**
