### PR TITLE
Third commit. Added to TEAM.md

### PR DESCRIPTION
**Pull request by lh536**

### CODE REVIEW

**Review by EYRAM565 — APPROVED** [review]

**Review by sarathkumar6 — APPROVED** [review]

**Review by nishanknavelkar — APPROVED** [review]

**Review by Akshay2996 — APPROVED** [review]
This is fine because it doesn't cause a conflict  with other PR

**Review by michaelcosj — APPROVED** [review]

**Review by sammjainn — APPROVED** [review]

**Review by pranavgoel29 — APPROVED** [review]

**Review by NahuelAlfano — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Conflict!

**Review by nishanknavelkar — APPROVED** [review]
Looks good

**Comment by lh536** [comment]
Conflict already solved.

**Comment by sammjainn** [comment]
Hey, merge conflicts may occur again and again, so please contact @johnjacobkenny or @sarathkumar6 so that they can merge your PR as soon as you resolve conflicts

**Comment by johnjacobkenny** [comment]
Again conflict :sweat_smile:

**Review by michaelcosj — APPROVED** [review]

**Comment by UnevenCoder** [comment]
Again merge conflict 😅

**Comment by lh536** [comment]
Again solved! 😃

**Comment by johnjacobkenny** [comment]
Thanks @lh536 hope it was a wonderful experience :smile: 

Thanks team for review

**Comment by lh536** [comment]
> Thanks @lh536 hope it was a wonderful experience 😄
> 
> Thanks team for review

Yes, Kenny! It was...! it doesn't matter if a conflict occurs again... I'll solve it... I'm learning it's better now when we are starting than later 😃

**Pull request merged**
