### PR TITLE
Third PR : added description to Team.md

### PR DESCRIPTION
**Pull request by JilvaSheth**

### CODE REVIEW

**Review by ad3rinto — APPROVED** [review]
Looks good.

**Comment by JilvaSheth** [comment]
> Looks good.

Thanks. Also, I've resolved the conflicts. I guess it can be merged now after 1 more approval.

**Review by UnevenCoder — APPROVED** [review]
Good to go for now

**Review by Akshay2996 — APPROVED** [review]
Approved👍

**Comment by Sheetal777** [comment]
@JilvaSheth Resolve the merge conflicts by clicking on 'Resolve Conflicts'? https://www.youtube.com/watch?v=U2bOwEY-vKo&t=145s

**Comment by Sheetal777** [comment]
@JilvaSheth Resolve the merge conflicts by clicking on 'Resolve Conflicts'? https://www.youtube.com/watch?v=U2bOwEY-vKo&t=145s

**Comment by Akshay2996** [comment]
Hi @JilvaSheth resolve your merge conflict by seeing the [Wiki Page](https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts) or watch a youtube video as mentioned by @Sheetal777

**Comment by JilvaSheth** [comment]
> Hi @JilvaSheth resolve your merge conflict by seeing the [Wiki Page](https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts) or watch a youtube video as mentioned by @Sheetal777

Yes, sure I'll resolve it by today evening. Since I don't have my laptop with me right now.

**Comment by JilvaSheth** [comment]
I will not be able to complete the procedure of conflict resolution due to some reasons for now. So, I've closed it for now. Will repeat the whole process again and will open another PR. Thanks, everyone for the support :)

**Pull request closed without merging**
