### PR TITLE
Fix PDF break, margin, twitter emojis

### PR DESCRIPTION
**Pull request by PuruVJ**
## Description
- Original emojis replaced with Twitter Emojis
- Weird Margin and centering issue fixed
- Fixed content break when PDF wraps to the other page
- Every build produces a `hello.html` in the device's `temp` folder, where it can be inspected

Check out `simon.pdf` in TwindleLibrary folder

## Attach Screenshot
image

### CODE REVIEW

**Comment by PuruVJ** [comment]
Closes #621

**Comment by PuruVJ** [comment]
Here's the PDf itself
[simon.pdf](https://github.com/twindle-co/twindle/files/5493003/simon.pdf)

**Comment by PuruVJ** [comment]
Ammendment: The page break issue can't be **solved**. Browser will **try** to avoid if it can. The chances of page breaks are still there, but it will be much more graceful

**Comment by johnjacobkenny** [comment]
Did you try the div with specific height

**Comment by tolgaerdonmez** [comment]
@johnjacobkenny @PuruVJ 
btw page breaks are not important for kindle I believe.

**Comment by PuruVJ** [comment]
@tolgaerdonmez PDfs are rigid, just like the web of 1990s. They act more like images than content, so yes, page breaks would count

**Comment by tolgaerdonmez** [comment]
I meant the ones converted to kindle format.

**Comment by PuruVJ** [comment]
@tolgaerdonmez Yeah, the AZWs don't care about them

**Pull request merged**
