### PR TITLE
Add myself to Team

### PR DESCRIPTION
**Pull request by PuruVJ**
## Description

I have no idea why those 9 extra commits are here.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
@proful please let us know why these extra commits are coming? I too faced it for my PR. I think it has something to do with squashing..

**Comment by johnjacobkenny** [comment]
@PuruVJ I think we should create sub branches when we work on something. That way main won't be affected and only our sub branch commits will show up

**Comment by PuruVJ** [comment]
@johnjacobkenny can you merge it?

**Comment by PuruVJ** [comment]
Having extra commits won't affect anything, as those commits have already been merged

**Review by RafaelBatman55 — APPROVED** [review]

**Comment by PuruVJ** [comment]
Hi @proful can you merge it?

**Comment by proful** [comment]
This PR needs more work.

There are so many deletion/addition. Only your changes should be shown.

**Review by johnjacobkenny — APPROVED** [review]
@proful I think a lot of the changes are whitespace, overall LGTM.

**Comment by proful** [comment]
Merging this time.

But too much changes better to avoid.

**Pull request merged**
