### PR TITLE
fix table and remove duplicated members

### PR DESCRIPTION
**Pull request by uplancer**

### CODE REVIEW

**Review by pranavgoel29 — COMMENTED** [review]
Still there are some duplicate lines please remove them too.

**Comment by uplancer** [comment]
> Still there are some duplicate lines please remove them too.

Done.
I think it's better for contributors to use this tool https://stackedit.io/app to edit and add to the tables.

**Review by pranavgoel29 — COMMENTED** [review]
still there are some line where location is in their name section,so please remove the location from name section and put it in description section.

**Comment by uplancer** [comment]
Done.
Thanks @pranavgoel29 for the help :)

**Comment by johnjacobkenny** [comment]
Is this same as a previous merged issue?

**Comment by pranavgoel29** [comment]
@uplancer you can close this PR the issue has been solved

**Pull request closed without merging**
