### PR TITLE
docs: updating FAQ with tutorials and tips recopiled from github issues

### LINKED ISSUE #242: ONBOARDING.md
Create a onboarding docs

What to do next after joining?

Step by step instruction

1. follow twitter
2. sub YT
3. join discord
4. fork github
5. first pr
6. second pr
7. third pr

@piratelicorne

### PR DESCRIPTION
**Pull request by piratelicorne**
closes #242

### CODE REVIEW

**Comment by arthurbuhl** [comment]
> Use these keywords to make your PR close automatically once is merged.

Hi, actually the wordings here is not correct. A PR is always closed once it is merged, but when an **issue** is linked to a PR using the keywords, then that **issue** is also closed automatically once the PR is merged.

Regards!

**Comment by johnjacobkenny** [comment]
@piratelicorne please also in the description add the message "closes #x #y #z" to auto close the issues once this is merged

**Comment by piratelicorne** [comment]
I'm on it

**Comment by piratelicorne** [comment]
Hi @johnjacobkenny , I corrected it :)

**Comment by johnjacobkenny** [comment]
Great, thanks @piratelicorne 🥳

**Pull request merged**
