### PR TITLE
Changes in the background-clip

### PR DESCRIPTION
**Pull request by shekhar10feb**
## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by shekhar10feb** [comment]
scr
 Changed from -webkit-background-clip to background-clip

**Comment by johnjacobkenny** [comment]
> scr
> Changed from -webkit-background-clip to background-clip

Could you explain the thought process why you changed, so others might understand

**Comment by shekhar10feb** [comment]
home1
 This was showing problem.

**Review by EYRAM565 — APPROVED** [review]

**Review by KiranDon — APPROVED** [review]

**Comment by shekhar10feb** [comment]
@proful @johnjacobkenny Please check it and merge it.

**Pull request merged**
