### PR TITLE
Create franklinulrich.md

### PR DESCRIPTION
**Pull request by frankiefab100**
About me

### CODE REVIEW

**Review by RafaelBatman55 — APPROVED** [review]

**Review by tusharkandpal — CHANGES_REQUESTED** [review]
Please change file name to `franklinulrich.md` to proceed.

**Comment by frankiefab100** [comment]
Alright, it has been updated

**Comment by shekhar10feb** [comment]
It's looking good

**Comment by tusharkandpal** [comment]
I meant the actual file name, not the title😅

**Comment by frankiefab100** [comment]
@tusharkandpal okay, thanks. I will resolve that

**Review by PrasoonPratham — APPROVED** [review]

**Review by UnevenCoder — APPROVED** [review]
good job

**Review by Akshay2996 — APPROVED** [review]

**Pull request merged**
