### PR TITLE
Create Alasi.md

### PR DESCRIPTION
**Pull request by Holaryeankar007**

### CODE REVIEW

**Comment by proful** [comment]
Thanks for this PR.

U need 2 code review approval.

Approach others in twitter group or discord channel (https://discord.com/invite/jBj2zMR)

Post ur pr link in those grp.

**Comment by rkumar1904** [comment]
All Good

**Review by thunder-coding — APPROVED** [review]

**Review by tusharkandpal — COMMENTED** [review]
rename file to `alasi.md` please

**Review by thunder-coding — CHANGES_REQUESTED** [review]
Change name to lowercase

**Comment by tusharkandpal** [comment]
@Holaryeankar007 you need to change the file name from `Alasi.md` to `alasi.md` for it to be approved

**Review by UnevenCoder — APPROVED** [review]
Since the site is specific try to house in details like
I like ...
I am learning ..,
to make the file personalised for you :)
'

**Comment by UnevenCoder** [comment]
Lower case file necessary too :)

**Review by tusharkandpal — APPROVED** [review]

**Review by tusharkandpal — CHANGES_REQUESTED** [review]
you didn't closed the table

**Comment by Holaryeankar007** [comment]
i have corrected that

**Review by tusharkandpal — APPROVED** [review]
good job 👍

**Review by thunder-coding — APPROVED** [review]
👍👍

**Review by UnevenCoder — APPROVED** [review]
Good job

**Pull request merged**
