### PR TITLE
[USER ACTION] Update README.md

### PR DESCRIPTION
**Pull request by Pa1sathvik**
Spelling correction.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
@Pa1sathvik Thank you for the pull request. I think there is an issue with your version being slightly older than the repository. Could @sarathkumar6 or @Sheetal777 help out with instructions?

**Comment by Sheetal777** [comment]
Yes, @johnjacobkenny this issue has been resolved earlier. I would request @Pa1sathvik to refresh the Readme file and re-check the spelling. If you will have any confusions, visit here.

**Comment by johnjacobkenny** [comment]
Yes, @Sheetal777 if you have details on how @Pa1sathvik can fetch the latest version and resolve the conflict and update this PR, please mention :slightly_smiling_face:

**Comment by thunder-coding** [comment]
You can close this pull request now @Pa1sathvik and delete your branch and create a fresh new fork

**Comment by Sheetal777** [comment]
Hey @Pa1sathvik  
If you want to continue with this one: To get the latest one and reset it, use these commands:

git fetch origin
git reset --hard origin/[tag/branch/commit-id] 

PS: usually, the tag/branch/commit-id is "master" only.

Or just delete the branch and make a new fork as @thunder-coding said.

**Comment by proful** [comment]
@Pa1sathvik close this pr if you are not planning to fix it.

**Pull request closed without merging**
