### PR TITLE
sippeybro.md added

### PR DESCRIPTION
**Pull request by sippeybro**

### CODE REVIEW

**Comment by proful** [comment]
Thanks for this PR.

U need 2 code review approval.

Approach others in twitter group or discord channel (https://discord.com/invite/jBj2zMR)

Post ur pr link in those grp.

**Review by sippeybro — COMMENTED** [review]
Re

**Review by Rakesh-4 — COMMENTED** [review]
Hey, sippey pls pull the latest changes and update the team.md with table format.

All the info has to go in between pipe symbol(|). You can just follow the format

**Review by EYRAM565 — APPROVED** [review]

**Review by UnevenCoder — APPROVED** [review]
Good job ,should be merged soon :)

**Pull request merged**
