### PR TITLE
Update javaScript.md

### PR DESCRIPTION
**Pull request by shekhar10feb**
## Description
Wrote some questions their answers. I encourage everyone also to write questions or if you their answers there. 

## Attach Screenshot
this

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Review by Akshay2996 — APPROVED** [review]
@shekhar10feb Great work. It's very important for everyone to see this file if they are having some problems.

**Comment by shekhar10feb** [comment]
@Akshay2996 Thank you

**Review by Akshay2996 — CHANGES_REQUESTED** [review]
Please use separate PR for the separate changes. It will be easy for us to understand which file is effected. JavascriptCode.md should be separate from others **(no dependencies on the other files)** for the changes so that we can review the file appropriately.

**Comment by shekhar10feb** [comment]
> 
> 
> Please use separate PR for the separate changes. It will be easy for us to understand which file is effected. JavascriptCode.md should be separate from others **(no dependencies on the other files)** for the changes so that we can review the file appropriately.

Please suggest how can I do it because every time other's PR also get attached to with new PR

**Review by proful — CHANGES_REQUESTED** [review]
Only raise PR which contains this code change.

Watch https://www.youtube.com/watch?v=OMmZJW-AHiE

**Pull request closed without merging**
