### PR TITLE
deleted some text & added header files

### PR DESCRIPTION
**Pull request by tusharkandpal**
1. Removing the extra lines.
2. added header files

### CODE REVIEW

**Comment by proful** [comment]
Screen shots?

**Comment by tusharkandpal** [comment]
In issue #274 @proful 

Do I need to add them as files as well?

**Comment by johnjacobkenny** [comment]
@tusharkandpal  There are some lines deleted from the FAQ file?

**Review by UnevenCoder — CHANGES_REQUESTED** [review]
Why removing lines from FAQ 👀👀

**Comment by tusharkandpal** [comment]
Yes those were copied by someone again mistakenly

**Review by UnevenCoder — APPROVED** [review]
Cool then good job 👍

**Review by piratelicorne — APPROVED** [review]
Approved, you have 2 approvals now, this one can be merged.

**Pull request merged**
