### PR TITLE
1st pr layomi

### LINKED ISSUE #267: Rename firstpr/Layomi.md
Rename it to `layomi.md`

Also please write "closes #267" in description of PR to automatically close this issue

### PR DESCRIPTION
**Pull request by shekhar10feb**
Close #267

### CODE REVIEW

**Comment by shekhar10feb** [comment]
> 
> 
> _No description provided._

Issue #267

**Comment by pranavgoel29** [comment]
you have to change the file name from Layomi.md to layomi.md

**Review by pranavgoel29 — CHANGES_REQUESTED** [review]
@shekhar10feb you have to change the file name from Layomi.md to layomi.md

**Comment by shekhar10feb** [comment]
> 
> 
> @shekhar10feb you have to change the file name from Layomi.md to layomi.md
I did on vs code and then sent pull request.

**Review by pranavgoel29 — APPROVED** [review]
Good to go now.

**Review by nishanknavelkar — APPROVED** [review]
Congrats on your first PR

**Comment by shekhar10feb** [comment]
> Congrats on your first PR
Thank you

**Review by tusharkandpal — APPROVED** [review]
Yups, all set. 👍 close #267

**Pull request merged**
