### PR TITLE
Verify first-interaction action

### PR DESCRIPTION
**Pull request by ni3-kdm**

### CODE REVIEW

**Comment by Akshay2996** [comment]
Hi @ni3-kdm Just a question?
Why did you remove the greetings.yml Is this the github-action that is causing the issue?

**Comment by johnjacobkenny** [comment]
@ni3-kdm please share your findings as the description. Also curious if this will be resolved by upstream if we just wait for sometime

**Comment by ni3-kdm** [comment]
> Hi @ni3-kdm Just a question?
> Why did you remove the greetings.yml Is this the github-action that is causing the issue?

Just verifying the changes, whether it's happening due to greetings.yml file or npm version. We are not merging this PR. I'm closing this PR. The root cause of this checks failing is in [first-interaction](https://github.com/marketplace/actions/first-interaction). We should wait for their PR to merge. For now, we should disable first-interaction action from our repo actions.

**Comment by johnjacobkenny** [comment]
@ni3-kdm since this is going on for sometime, lets just remove it for the time being

**Pull request closed without merging**
