### PR TITLE
feat: Twindle homepage proposal

### PR DESCRIPTION
**Pull request by piratelicorne**
Hi, this is my proposal for the webpage :)

Screen Shot 2020-10-22 at 04 23 29

### CODE REVIEW

**Comment by piratelicorne** [comment]
these options change color when the user hovers

Screen Shot 2020-10-22 at 04 56 49

Screen Shot 2020-10-22 at 04 56 54

**Review by shekhar10feb — APPROVED** [review]

**Comment by shekhar10feb** [comment]
Looks nice!!

**Comment by EYRAM565** [comment]
nice.

**Comment by stamenkovic-dev** [comment]
Wow! I really like it. Nice design, clean code...

**Comment by proful** [comment]
image

Your entry should be homepage3

**Comment by piratelicorne** [comment]
files moved

**Review by proful — APPROVED** [review]
Looking good

**Pull request merged**
