### PR TITLE
Added a link to the CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by thunder-coding**
Added a link to CONTRIBUTING.md file so that visitors who also want to contribute can

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
@thunder-coding the way you added the link is correct in HTML sense, but not so much in a markdown sense. Could you take a look at the markdown docs and see how you might link it in markdown syntax? After you figure that out, bonus points if you can find out details on whether github provides any specific way to link within files in a repo. :smiley:

**Comment by thunder-coding** [comment]
I think we should go by the rule 
```
If it worka don't touch it 😂
```

**Comment by johnjacobkenny** [comment]
You don't need to close the PR, you can just add commits and push to your fork, and it will come up here automatically!

And yes, the idea is to learn something new, I just shared it since it may be a learning experience, and also you don't seem to be a beginner :smiley:

**Comment by thunder-coding** [comment]
I just didn't wanted to fill up the pending PR list, that's why I closed it for a while.

**Comment by johnjacobkenny** [comment]
Take a look at this, I think that will solve the deep linking issue :) https://github.blog/2013-01-31-relative-links-in-markup-files/

**Comment by thunder-coding** [comment]
Means I have to deep link it??

Heard of this term first time

**Comment by johnjacobkenny** [comment]
Yes, this looks good :smile:

**Pull request merged**
