### PR TITLE
Create prasanna.md

### PR DESCRIPTION
**Pull request by Prasann123**

### CODE REVIEW

**Comment by pranavgoel29** [comment]
Congrats on your first PR. 🥳

**Comment by proful** [comment]
Congratulations on your first pr

**Comment by Prasann123** [comment]
> Congrats on your first PR. 🥳

Thanks for the help Pranav much appreciated

**Comment by Prasann123** [comment]
> Congratulations on your first pr

Thanks Proful very much excited to learn front end via this project. great initiative

**Pull request merged**
