### PR TITLE
updated pranav.md for a video.

### PR DESCRIPTION
**Pull request by pranavgoel29**
I am making a video on how to make a PR directlt from vscode using GUI.

### CODE REVIEW

**Review by UnevenCoder — APPROVED** [review]
All good 👍

**Comment by piratelicorne** [comment]
Awesome! please tag me or @Sheetal777  when it's done so we can reference it in the FAQ page, also upload it in the Twindle YT channel.

Thank you!

**Comment by pranavgoel29** [comment]
> Awesome! please tag me or @Sheetal777  when it's done so we can reference it in the FAQ page, also upload it in the Twindle YT channel.
> 
> Thank you!

@piratelicorne and @Sheetal777 can any one of you add this video link in the FAQs page.
Here's the link:-
https://youtu.be/ZQqfZt1RIpA

**Comment by tusharkandpal** [comment]
@pranavgoel29 what's this PR is about ? Can you tell again

**Comment by piratelicorne** [comment]
I reference the video in the FAQ page -> #306

**Review by Sheetal777 — APPROVED** [review]

**Pull request closed without merging**
