### PR TITLE
Readable timestamp

### LINKED ISSUE #622: PDF Time stamp should be readable
image

05 Nov 2020 5 PM IST 

Timezone should be based on user who run the program.

Twitter timestamp are UTC needs to be converted to local TZ.

### PR DESCRIPTION
**Pull request by PuruVJ**
## Description
The date format has been fixed
Closes #622 
## Attach Screenshot
image

### CODE REVIEW

**Comment by PuruVJ** [comment]
Anybody has idea how to get rid of all those extra commits? They have all been done already

**Comment by johnjacobkenny** [comment]
Having the branch isn't helping, right? @PuruVJ

**Comment by proful** [comment]
@PuruVJ please close this and raise a clean pr.

**Comment by PuruVJ** [comment]
> Having the branch isn't helping, right? @PuruVJ

Exactly!

**Comment by PuruVJ** [comment]
> @PuruVJ please close this and raise a clean pr.

How do I raise a **clean** pr? What is a clean pr?

**Comment by proful** [comment]
Create a new branch

Pull the latest change

Make your code change

Raise PR

After PR merged delete the branch

Repeat

**Comment by PuruVJ** [comment]
That's what I did for this

**Comment by arthurbuhl** [comment]
Why do you have so many changes for just time format update?

**Comment by johnjacobkenny** [comment]
@arthurbuhl in the merge process I think we are now squashing the commits. This causes an issue when we sync back to our fork, which would add merge commits to our main branch. I don't know for sure if this is whats happening.

**Comment by arthurbuhl** [comment]
Oh, I see.

**Pull request closed without merging**
