### PR TITLE
Created can.md

### PR DESCRIPTION
**Pull request by cankocman**
First PR / Local desktop PR

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Are you having trouble with the PR

**Comment by cankocman** [comment]
Yeah i was because i was trying to PR from local desktop and typed wrong links over and over :D

**Comment by johnjacobkenny** [comment]
Oh, got it sorted out? 🙂

**Comment by cankocman** [comment]
Yeah, but somehow i am still not a contributor. Don't get why.

**Pull request merged**
