### PR TITLE
First PR!

### PR DESCRIPTION
**Pull request by Bread-N-Water**

### CODE REVIEW

**Comment by pranavgoel29** [comment]
@Bread-N-Water use lowercase lettering aand avoid using of symbols and numbers.

**Comment by Bread-N-Water** [comment]
should I try to commit and create a new PR with these rules?

**Comment by pranavgoel29** [comment]
No you just have to change the file name in your forked repo then automatically it will reflect here.

**Comment by Bread-N-Water** [comment]
done!

**Comment by pranavgoel29** [comment]
Congrats it's good to go now 👍

**Comment by Bread-N-Water** [comment]
thanks a lot!, will try to make my 2nd PR from CLI

**Comment by johnjacobkenny** [comment]
Congrats @Bread-N-Water :partying_face: 

Thanks @pranavgoel29 for review :+1:

**Pull request merged**
