### PR TITLE
First section of Twindle Website 

### LINKED ISSUE #625: Set the New Hompage

### PR DESCRIPTION
**Pull request by UnevenCoder**
close #625 

Well hopefully this is the correct design

Figma file :
image
Coded Design : 
image

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by UnevenCoder** [comment]
Requesting @JoelVinayKumar & [ @vasu001 or @vasudeveloper001 ] and others reading this for a review :)

**Review by Akshay2996 — APPROVED** [review]
Looking nice😍

**Review by Akshay2996 — APPROVED** [review]
Nice work @UnevenCoder 👍

**Comment by UnevenCoder** [comment]
Thanks bro :)

**Review by PuruVJ — APPROVED** [review]
Looks good

**Comment by UnevenCoder** [comment]
Thanks
@johnjacobkenny @proful ready to merge

**Comment by shekhar10feb** [comment]
Amazing work

**Comment by UnevenCoder** [comment]
Thanks :)

**Pull request merged**
