### PR TITLE
new changes to add- case sensitive term

### PR DESCRIPTION
**Pull request by jahidhasanlinix**
For the naming convention

### CODE REVIEW

**Comment by arthurbuhl** [comment]
Personally, I don't think this is needed, as the naming convention already states all `lowercase` file name, then that implicitly means its `case sensitive`, right?

But I will leave it for other contributors to share their opinions. Regards!

**Comment by proful** [comment]
Agree @arthurbuhl

**Comment by proful** [comment]
@jahidhasanlinix close this pr if you are not planning to fix it.

**Comment by UnevenCoder** [comment]
Hey , if you aren't contributing please close the pr

**Comment by thunder-coding** [comment]
Please close this PR. Lots of PRs are pending and need to be checked. 

Hope you are understanding my concerns @jahidhasanlinix

**Pull request closed without merging**
