### PR TITLE
Second PR - Predrag

### PR DESCRIPTION
**Pull request by stamenkovic-dev**
according to Mellisa's video instructions

### CODE REVIEW

**Review by RafaelBatman55 — APPROVED** [review]

**Review by madhusudanbabar — APPROVED** [review]

**Review by RafaelBatman55 — APPROVED** [review]

**Review by nishanknavelkar — APPROVED** [review]

**Review by aesthytik — APPROVED** [review]

**Review by SunnyDev7 — APPROVED** [review]
Looks good to go!

**Comment by sarathkumar6** [comment]
Hey @stamenkovic-dev,
Good job. A suggestion the file name follows snake case. I see, barring a couple of files, all the files in the firstpr folder are in small case. And to keep the naming convention uniform, do you mind updating your file name from snake case to small case i.e., predragstamenkovic ?
Thanks.

**Comment by pranavgoel29** [comment]
Please change your file from `predrag_stamenkovic.md ` to `predragstamenkovic.md ` so naming can be uniform all along in folder.

**Comment by RafaelBatman55** [comment]
I think he chose this file name because our FAQ mention to do like that:

> Create a new file firstname_lastname.md inside the firstpr directory, commit your change and raise your first Pull Request.

**Comment by UnevenCoder** [comment]
> I think he chose this file name because our FAQ mention to do like that:
> 
> > Create a new file firstname_lastname.md inside the firstpr directory, commit your change and raise your first Pull Request.

Yup 
And other people have done thta tok he is not the first one

**Comment by stamenkovic-dev** [comment]
> I think he chose this file name because our FAQ mention to do like that:
> 
> 
> 
> > Create a new file firstname_lastname.md inside the firstpr directory, commit your change and raise your first Pull Request.

Thanks Rafael. Yes, that was according to FAQ, but also most of us beginners looked and was instructed by Melissa's video, which also has file like firstname_lastnamd.md

**Comment by pranavgoel29** [comment]
> > I think he chose this file name because our FAQ mention to do like that:
> > > Create a new file firstname_lastname.md inside the firstpr directory, commit your change and raise your first Pull Request.
> 
> Thanks Rafael. Yes, that was according to FAQ, but also most of us beginners looked and was instructed by Melissa's video, which also has file like firstname_lastnamd.md

I just checked Firstpr guide once again, and according to that the naming is ok 😄, sorry for prev comment as I haven't check the updated guide back then.

**Comment by thunder-coding** [comment]
Merge this PR @johnjacobkenny

**Comment by johnjacobkenny** [comment]
Good job team! 🥳

**Pull request merged**
