### PR TITLE
Update TEAM.md

### PR DESCRIPTION
**Pull request by Sheetal777**
PR #3

### CODE REVIEW

**Comment by Sheetal777** [comment]
@johnjacobkenny This one looks good to be merged :P

**Review by Rakesh-4 — APPROVED** [review]
looks good

**Comment by johnjacobkenny** [comment]
Lol @Sheetal777 reviewing her own PR 😂

**Comment by sarathkumar6** [comment]
@Sheetal777 oh lord....

**Comment by proful** [comment]
😂😂

**Pull request merged**
