### PR TITLE
Sending to kindle, TwindleLibrary, node-calibre, Nodemailer

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
## Description
Before approving the PR, help needed!

fixed a bug in helpers/logger.js
new cli flag -s to send email ( not working )

TwindleLibrary,
  - Creates a folder for all outputs, set within the .env file
  - utils/librar.js
  - getLibraryPath function to access the library path for all path
    operations

node-calibre,
  - converts pdf to epub,mobi,etc...

nodemailer,
  - sends email, but currently kindle doesn't download the file but no
    errors

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by proful** [comment]
@tolgaerdonmez Merging this code.

However I have reservations regarding converting pdf to epub and mobi.

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez Merging this code.
> 
> However I have reservations regarding converting pdf to epub and mobi. 

The conversion was just to send it to kindle in a proper format, but calibre does a good job on that I believe.

**Comment by proful** [comment]
We can send pdf isn't it?

Kindle supports pdf

**Comment by tolgaerdonmez** [comment]
> We can send pdf isn't it?
> 
> Kindle supports pdf

Yeah we can send pdf but manually, I couldn't send anything using Nodemailer.

**Pull request merged**
