### PR TITLE
Move franklinulrich.md to firstpr folder

### PR DESCRIPTION
**Pull request by lh536**

### CODE REVIEW

**Comment by proful** [comment]
This is not proper.

Lots of merge conflict information are there..

@lh536 you need to have a call with someone

**Comment by lh536** [comment]
> This is not proper.
> 
> Lots of merge conflict information are there..
> 
> @lh536 you need to have a call with someone

Yes, @proful totally agree... I have so much conflicts with git/github...

**Comment by naveenkala** [comment]
> > This is not proper.
> > Lots of merge conflict information are there..
> > @lh536 you need to have a call with someone
> 
> Yes, @proful totally agree... I have so much conflicts with git/github...

Your pr was changing 16 files, if you're a beginner try changing 1 or 2 files only then do PR, as it would be easier for all to resolve any error.

**Comment by lh536** [comment]
> > > This is not proper.
> > > Lots of merge conflict information are there..
> > > @lh536 you need to have a call with someone
> > 
> > 
> > Yes, @proful totally agree... I have so much conflicts with git/github...
> 
> Your pr was changing 16 files, if you're a beginner try changing 1 or 2 files only then do PR, as it would be easier for all to resolve any error.

Okay... good advice! I'll do it that way! Thank you!

**Comment by lh536** [comment]
How can I return to the current twindle-co repo state?

**Comment by naveenkala** [comment]
> How can I return to the current twindle-co repo state?
> I use `git pull upstream main` but it doesn't seems to work...
git fetch upstream
git merge upstream/main

**Comment by naveenkala** [comment]
> How can I return to the current twindle-co repo state?
> I use `git pull upstream main` but it doesn't seems to work...

git fetch upstream
git merge upstream/main

**Comment by lh536** [comment]
> > How can I return to the current twindle-co repo state?
> > I use `git pull upstream main` but it doesn't seems to work...
> 
> git fetch upstream
> git merge upstream/main

I made it... but still a conflict...
image
image
I don't know what and why is this happening...

**Pull request closed without merging**
