### PR TITLE
Create tushar.md

### PR DESCRIPTION
**Pull request by tusharkashyap63**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Thanks @tusharkashyap63 :+1:

**Comment by pranavgoel29** [comment]
@johnjacobkenny can you help me when I am syncing my forked repo this file(TUSHAR.md) is colliding with a file named 'tushar.md'

**Comment by johnjacobkenny** [comment]
@Sheetal777 would you like to help out here 🙂

**Comment by johnjacobkenny** [comment]
> @Sheetal777 would you like to help out here 🙂

Oh sorry, I think it's fixed now! 😅

**Comment by pranavgoel29** [comment]
@vijaya-bhaskar I already fixed it.

**Pull request merged**
