### PR TITLE
3 PR

### PR DESCRIPTION
**Pull request by lorennaleon**

### CODE REVIEW

**Review by piratelicorne — APPROVED** [review]
Approved

**Review by PrasoonPratham — COMMENTED** [review]
image
Any reason as to why there are so many changes

**Comment by lorennaleon** [comment]
> image
> Any reason as to why there are so many changes


I put my name in the middle and the other lines went lower

**Comment by proful** [comment]
That's not proper way. Changes should be minimal and it will help beginners.

**Comment by PrasoonPratham** [comment]
> > image
> > Any reason as to why there are so many changes
> 
> I put my name in the middle and the other lines went lower

suggest you to close this pr and do it the right way.

**Comment by lorennaleon** [comment]
> That's not proper way. Changes should be minimal and it will help beginners.

fixed thanks

**Review by proful — COMMENTED** [review]
Looks good

**Comment by lorennaleon** [comment]
> suggest you to close this pr and do it the right way.

fixed

**Comment by arthurbuhl** [comment]
This looks good to me. I think this can be merged now. :+1: 

I think this point can be added in CR checklist, to add the name in end of the list so that there are less changes to the original file.

**Review by pranavgoel29 — APPROVED** [review]
It is good to go and please take a look at the issue #493 and try to solve it.

**Comment by shekhar10feb** [comment]
Beginner part is showing 2 times....please check it

**Pull request merged**
