### PR TITLE
third PR adewale

### PR DESCRIPTION
**Pull request by princehaybee**

### CODE REVIEW

**Comment by ni3-kdm** [comment]
**- Table format not showing correctly.** Can you correct it?

pr

**Comment by princehaybee** [comment]
I have just edited it again. Kindly check if I have done the right thing.

**Review by johnjacobkenny — APPROVED** [review]

**Review by EYRAM565 — APPROVED** [review]

**Comment by tusharkandpal** [comment]
@johnjacobkenny are those hyphens not mandatory in table format, because those are removed?

**Comment by johnjacobkenny** [comment]
> @johnjacobkenny are those hyphens not mandatory in table format, because those are removed?

Ohh I'm not sure, but I missed that! Thanks for catching it!

**Review by johnjacobkenny — CHANGES_REQUESTED** [review]
image

**Comment by arthurbuhl** [comment]
The issue is to display table we need the middle part like:

```md
| Name       | Description |
| ---------- | ----------- |
| A | B |
```

This looks like:

| Name       | Description |
| ---------- | ----------- |
| A | B |

<hr/>

But in your commit you have deleted the middle part `| ---------- | ----------- |` like:

```md
| Name       | Description |
| A | B |
```

Due to which it looks now like:

| Name       | Description |
| A | B |

<hr/>

So, just add that middle part back again and the Table format will work fine. Thanks!

**Review by piratelicorne — COMMENTED** [review]
I see the table back
Screen Shot 2020-10-21 at 20 18 22

**Review by piratelicorne — COMMENTED** [review]
2 files reviewed

**Review by lh536 — APPROVED** [review]

**Review by lh536 — APPROVED** [review]
I think everything is fine.

**Pull request merged**
