### PR TITLE
added myself in teams

### PR DESCRIPTION
**Pull request by krishnadevz**

### CODE REVIEW

**Review by krishnadevz — COMMENTED** [review]
updated stuff

**Review by EYRAM565 — APPROVED** [review]

**Comment by EYRAM565** [comment]
kindly resolve the conflicting files.

**Review by krishnadevz — COMMENTED** [review]
resolved file conflicts

**Comment by Na-ilah** [comment]
good to go

**Review by RafaelBatman55 — APPROVED** [review]

**Pull request merged**
