### PR TITLE
Add pkg json, eslint, prettier confis for twindle-cli

### PR DESCRIPTION
**Pull request by itsmeAB**
Added the following configs for twindle/playground/cli/twindle-cli
1. npm init
2. package json
3. eslint/prettier config

@proful please review.

### CODE REVIEW

**Comment by arthurbuhl** [comment]
I don't think we should add "eslint/prettier config" for now, based on the same reason as mentioned in #103 by @proful 
Please review this point once. Thanks.

**Comment by proful** [comment]
Sorry @arthurbuhl 
2 weeks back we are setting up.
now it is time to have some coding style in place. I think we need to follow some structure.

Going forward my intention is for everyone to work together in playground/cli/twindle-cli

Till now all created independently.

Your thoughts?

**Comment by arthurbuhl** [comment]
Ok, then its fine. Then we will be also adding EditorConfig, right?

**Comment by proful** [comment]
sure however I never used EditorConfig myself 😊

interested to know more.
https://editorconfig.org/ ?

**Comment by arthurbuhl** [comment]
Ok, then we shouldn't use it for now, maybe in future. Let's just go with eslint/prettier only for now.

**Comment by proful** [comment]
this is an important change. approved & merging.

**Comment by itsmeAB** [comment]
@arthurbuhl @proful thanks for merging.

**Pull request merged**
