### PR TITLE
This is my second PR

### PR DESCRIPTION
**Pull request by mrjuoss**

### CODE REVIEW

**Comment by proful** [comment]
Ask in Twitter group by giving link to this pr for review and approval. 2 approval needed.

**Review by sammjainn — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
There is a merge conflict, please fix it

**Comment by Sheetal777** [comment]
Hey @mrjuoss Could you try to resolve the merge conflicts by clicking on 'Resolve Conflicts'? If there are further problems, drop the screenshots. We will help out.

**Comment by Sheetal777** [comment]
https://www.youtube.com/watch?v=U2bOwEY-vKo&t=145s @mrjuoss

**Comment by johnjacobkenny** [comment]
Closing this since there is no response. Please reopen as necessary.

**Pull request closed without merging**
