### PR TITLE
Third PR - TEAM.md updated

### PR DESCRIPTION
**Pull request by stamenkovic-dev**

### CODE REVIEW

**Comment by UnevenCoder** [comment]
There's some conflicts that you might need to solve before approval

**Comment by piratelicorne** [comment]
@stamenkovic-dev please fix your conflicts

**Review by piratelicorne — COMMENTED** [review]
please fix your conflicts

**Comment by johnjacobkenny** [comment]
Could someone @UnevenCoder @sammjainn or anyone help @stamenkovic-dev out with the conflict?

**Pull request closed without merging**
