### PR TITLE
Added loading spinner #729

### PR DESCRIPTION
**Pull request by michaelcosj**
## Description
Added loading spinner with [ora](https://github.com/sindresorhus/ora) for issue #729 
It displays a loading progress spinner in the CLI while the program's processes are running

## Attach Screenshot
Screenshot from 2020-11-10 11-01-13
Screenshot from 2020-11-10 11-03-18
Screenshot from 2020-11-10 11-03-39
Screenshot from 2020-11-10 11-04-26

### CODE REVIEW

**Comment by PuruVJ** [comment]
Looks good

**Review by PuruVJ — APPROVED** [review]

**Review by tolgaerdonmez — COMMENTED** [review]
Very nice!

**Review by tolgaerdonmez — APPROVED** [review]
Nice!

**Comment by johnjacobkenny** [comment]
Nice!

**Pull request merged**
