### PR TITLE
Adding my picture

### PR DESCRIPTION
**Pull request by MrVoicer**
## Attach Screenshot

premnath

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Please also link this image in the team.md file, and get 2 review approvals

**Comment by proful** [comment]
@twindle-co/developer please review

**Review by RafaelBatman55 — APPROVED** [review]

**Comment by arthurbuhl** [comment]
> 
> 
> Please also link this image in the team.md file, and get 2 review approvals

Image is not added to team.md file yet. This PR can't be approved till then.

**Review by ni3-kdm — CHANGES_REQUESTED** [review]
@MrVoicer Please add your image path in the team.md. Add description and screenshot for the done changes.

**Comment by piratelicorne** [comment]
👀

**Comment by proful** [comment]
pending since long

**Pull request closed without merging**
