### PR TITLE
3rd PR: added my github url to the TEAM.md file

### PR DESCRIPTION
**Pull request by ad3rinto**
added my github url to the TEAM.md file

### CODE REVIEW

**Comment by proful** [comment]
Thanks for this PR.

U need 2 code review approval.

Approach others in twitter group or discord channel (https://discord.com/invite/jBj2zMR)

Post ur pr link in those grp.

**Comment by ad3rinto** [comment]
Thanks @proful . Will do that asap.

**Review by thunder-coding — APPROVED** [review]

**Comment by thunder-coding** [comment]
I have approved the changes, but you need to solve the merge conflicts in docs/TEAM.md

**Review by EYRAM565 — APPROVED** [review]

**Comment by EYRAM565** [comment]
conflicting files

**Comment by ad3rinto** [comment]
Conflict sorted.

**Review by EYRAM565 — APPROVED** [review]

**Comment by EYRAM565** [comment]
nice. congrats

**Review by pranavgoel29 — CHANGES_REQUESTED** [review]
You have to pull the changes from the main repo to your forked repo as I can see that there are many names which have been repeated in your file and please add you name in Table format you can write it as follows.

- | [Micheal Aderinto](https://github.com/ad3rinto) | I'm based in Manchester UK. Hoping this will be by first step in the world of solving world problems with code. |

**Comment by ad3rinto** [comment]
@pranavgoel29 Done. Please review. Thanks

**Review by pranavgoel29 — CHANGES_REQUESTED** [review]
Please remove line from number 3 to 25 as they are extra if you any guide you can ask for it.

**Review by thunder-coding — CHANGES_REQUESTED** [review]
Don't harrass the table view please :laughing:

**Comment by ad3rinto** [comment]
Deleting this repository and recreating since I changed my username it has caused some confusion.

**Pull request closed without merging**
