### PR TITLE
Update TEAM.md

### PR DESCRIPTION
**Pull request by kambleaa007**
Added my name

### CODE REVIEW

**Review by tusharkandpal — APPROVED** [review]

**Review by madhusudanbabar — APPROVED** [review]

**Review by johnjacobkenny — APPROVED** [review]

**Review by Akshay2996 — APPROVED** [review]

**Comment by sarathkumar6** [comment]
Please resolve the merge conflict and remove the label when resolved. @kambleaa007  Thanks.

**Comment by kambleaa007** [comment]
Conflict Resolved

**Review by pranavgoel29 — APPROVED** [review]

**Comment by tusharkandpal** [comment]
Line 70 to 73 are extra.. can you please recheck it?

**Comment by kambleaa007** [comment]
> Line 70 to 73 are extra in docs/FAQ.md, can you please recheck it?

I checked it, I didn't modified FAQ.md file, do you mind to raise another issue for it

**Comment by kambleaa007** [comment]
Kindly get it Merged, to avoid unnecessary merge conflicts

**Comment by proful** [comment]
Don't put in mentor. After you bit active and your presence recognize you can make your self as mentor.

**Comment by tusharkandpal** [comment]
I fixed it in #316, approving yours

**Review by tusharkandpal — APPROVED** [review]

**Comment by kambleaa007** [comment]
did the required changes, Kindly get it Merged, to avoid unnecessary merge conflicts

**Review by tusharkandpal — APPROVED** [review]

**Comment by kambleaa007** [comment]
Thanks @proful

**Pull request merged**
